window.BNTI_DATA = {
  "meta": {
    "generated_at": "2026-02-10T11:14:16.751027",
    "main_index": 7.85,
    "status": "CRITICAL",
    "active_scan": true,
    "next_update": "2026-02-10T12:00:00",
    "version": "2.0.0"
  },
  "countries": {
    "Armenia": {
      "index": 3.68,
      "raw_score": 10.25,
      "events": [
        {
          "title": "Through metal and spirit: The birth of Ani Hovak’s ‘Paradise Birds’",
          "translated_title": "Through metal and spirit: The birth of Ani Hovak’s ‘Paradise Birds’",
          "link": "https://armenianweekly.com/2026/02/09/through-metal-and-spirit-the-birth-of-ani-hovaks-paradise-birds/",
          "date": "Mon, 09 Feb 2026 22:41:02 +0000",
          "category": "violent protest",
          "confidence": 0.8534048199653625,
          "weight": 5.973833739757538,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "85.3%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Armenia",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Slaughterhouse: Stamp No. 5",
          "translated_title": null,
          "link": "https://hetq.am/en/article/179665",
          "date": "Tue, 10 Feb 2026 11:30:00 +0400",
          "category": "violent protest",
          "confidence": 0.6107835173606873,
          "weight": 4.275484621524811,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "61.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Yervant Odian and the odious truth",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/02/09/yervant-odian-and-the-odious-truth/",
          "date": "Mon, 09 Feb 2026 22:52:02 +0000",
          "category": "violent protest",
          "confidence": 0.27546781301498413,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "27.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "The Armenian nation: A journey through the centuries",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/02/09/the-armenian-nation-a-journey-through-the-centuries/",
          "date": "Mon, 09 Feb 2026 18:46:42 +0000",
          "category": "violent protest",
          "confidence": 0.22198829054832458,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "22.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Armenia in 2025: Ambition, overreach and the limits of multi-vector diplomacy",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/02/09/armenia-in-2025-ambition-overreach-and-the-limits-of-multi-vector-diplomacy/",
          "date": "Mon, 09 Feb 2026 17:40:53 +0000",
          "category": "neutral news",
          "confidence": 0.2528161406517029,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Book Review: ‘Never Hide from the Devil’",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/02/09/book-review-never-hide-from-the-devil/",
          "date": "Mon, 09 Feb 2026 16:45:40 +0000",
          "category": "violent protest",
          "confidence": 0.29567185044288635,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "29.6%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Firebird and U.S. Government Announce Phase 2 of Armenia AI Megaproject, Scaling it to $4 Billion and 50,000 GPU in 2026",
          "translated_title": null,
          "link": "https://hetq.am/en/article/179669",
          "date": "Tue, 10 Feb 2026 14:30:00 +0400",
          "category": "humanitarian crisis",
          "confidence": 0.2001871019601822,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "20.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Vance Says Armenia Is Beautiful; Announces Sale of Drone Technology",
          "translated_title": null,
          "link": "https://hetq.am/en/article/179655",
          "date": "Mon, 09 Feb 2026 22:57:00 +0400",
          "category": "neutral news",
          "confidence": 0.4271708130836487,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "42.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Pashinyan Welcomes Vance to Armenia",
          "translated_title": null,
          "link": "https://hetq.am/en/article/179648",
          "date": "Mon, 09 Feb 2026 18:54:00 +0400",
          "category": "neutral news",
          "confidence": 0.1857680380344391,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "18.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Catholicos Aram I Launches AI Courses for Clergy",
          "translated_title": null,
          "link": "https://hetq.am/en/article/179646",
          "date": "Mon, 09 Feb 2026 17:11:00 +0400",
          "category": "peaceful diplomacy",
          "confidence": 0.2323458045721054,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Armenia Hasn&#039;t Received Any Money from Sale of L.A. Mansion Owned by Family of Former Finance Minister",
          "translated_title": null,
          "link": "https://hetq.am/en/article/179640",
          "date": "Mon, 09 Feb 2026 14:07:00 +0400",
          "category": "violent protest",
          "confidence": 0.2771243155002594,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "27.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Vance in Armenia Today for TRIPP Talks",
          "translated_title": null,
          "link": "https://hetq.am/en/article/179637",
          "date": "Mon, 09 Feb 2026 11:31:00 +0400",
          "category": "neutral news",
          "confidence": 0.2549057900905609,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "U.S. Policy in the South Caucasus: Armenia’s Strategic Value and Its Limits",
          "translated_title": null,
          "link": "https://hetq.am/en/article/179630",
          "date": "Mon, 09 Feb 2026 10:00:00 +0400",
          "category": "terrorist act",
          "confidence": 0.20827676355838776,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "20.8%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "US reaches nuclear deal with Armenia as Vance pushes peace dividend - Reuters",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMivAFBVV95cUxNT29NYnEwb1hoZ1gteDRFWHZtQ0xuR09mck9Jd25WZElRbjM3WXZmUi14RkNwRThwWkVsd2FfTjJxYzl1UV93cEgyVTdWdHNGRDU3b2E3X2J2R21STHhmUm1lQmRBRmlpekhOLV81MGdkN3dyMzkzXy1UTUJDeUpQRFR0TUVjeWlodWNxRWdGd2J2cTRBTV9yRXNFN1VxLVN6QUVoUWtGcktsVDBPZk4ta1A5dU9raHhuWmd3Tw?oc=5",
          "date": "Mon, 09 Feb 2026 10:12:42 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.5897173881530762,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "59.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Vance visits Armenia, a country no sitting U.S. president or vice president has gone to before - PBS",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMixgFBVV95cUxPQVhYUmEza1pRazY2QjFId2ZrMTdfV25pOUtkX2RmWm8tVnpuQ2UwSEpmem1URk9DVG1mdjVHOF9FVFIyTzVTTUw1NUR5bkM0VE1CYWxPbU9JaDNad2lTOWVfNUN6WnBRNVJoVHJwMkotQm5vZWJDNXNMWTFfck1faF94UmNzeUQtOUV4RnFTbmVvS1ZqUm85WkFIZ2dMRUtYcGFRR2lTdWYxRmQ3STczT2lUR2pGbThtRFJhM0RmWU9VY092dmfSAcsBQVVfeXFMTk5jdzU2MVZiX293NEJDWW12bFBROHF6X1p2UklTNkU4Wl9FYnFLelg2VEkzZC1Ya2ZWSmpoWU5zVzRoSW5pSmxud0R1LVQ3SElucjZGcmhqNWhhTng3a3FJVVItWkwwU3Jwd251dlBqUzMxdTZDYUJIY2F0STJCUUJKYXFnVUlSMVF2SGtvVUJzSDd2MVNNZXFVLV9rMm1Oa3pRUEdDT1pQaU5JUkx0Q3hIelYtV2NYak5qWEVEdlRsRUh5ZGFhSlhrOE0?oc=5",
          "date": "Tue, 10 Feb 2026 00:31:50 GMT",
          "category": "neutral news",
          "confidence": 0.2625454366207123,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "26.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        }
      ]
    },
    "Georgia": {
      "index": 4.67,
      "raw_score": 20.63,
      "events": [
        {
          "title": "Russia Detains Abkhaz Diaspora Representative Amid Passport Controversy",
          "translated_title": "Russia Detains Abkhaz Diaspora Representative Amid Passport Controversy",
          "link": "https://civil.ge/archives/720593",
          "date": "Mon, 09 Feb 2026 13:21:09 +0000",
          "category": "political crisis",
          "confidence": 0.9764279723167419,
          "weight": 5.858567833900452,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "97.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgian government drops university merger after public backlash",
          "translated_title": "Georgian government drops university merger after public backlash",
          "link": "https://oc-media.org/georgian-government-drops-university-merger-after-public-backlash/",
          "date": "Mon, 09 Feb 2026 14:44:20 +0000",
          "category": "political crisis",
          "confidence": 0.9323716759681702,
          "weight": 5.594230055809021,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "93.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Jailed Opposition Politician Nika Melia Faces New Charges",
          "translated_title": null,
          "link": "https://civil.ge/archives/720634",
          "date": "Mon, 09 Feb 2026 15:32:17 +0000",
          "category": "political crisis",
          "confidence": 0.8525272607803345,
          "weight": 5.115163564682007,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "85.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgia’s price wars: what’s really behind increasing costs",
          "translated_title": null,
          "link": "https://oc-media.org/georgias-price-wars-whats-really-behind-increasing-costs/",
          "date": "Tue, 10 Feb 2026 09:07:56 +0000",
          "category": "political crisis",
          "confidence": 0.6774287819862366,
          "weight": 4.064572691917419,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "67.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Tuesday, 10 February 2026",
          "translated_title": null,
          "link": "https://oc-media.org/tuesday-10-february-2026/",
          "date": "Tue, 10 Feb 2026 08:38:04 +0000",
          "category": "neutral news",
          "confidence": 0.24782352149486542,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "JD Vance visits Armenia in a historic first",
          "translated_title": null,
          "link": "https://oc-media.org/jd-vance-visits-armenia-in-a-historic-first/",
          "date": "Mon, 09 Feb 2026 17:41:05 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.181080162525177,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "18.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgia investigates circumstances of return and death of woman who fled Chechnya",
          "translated_title": null,
          "link": "https://oc-media.org/georgia-investigates-circumstances-of-return-and-death-of-woman-who-fled-chechnya/",
          "date": "Mon, 09 Feb 2026 12:50:05 +0000",
          "category": "military conflict",
          "confidence": 0.3259529769420624,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "32.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Kavelashvili claims Vance said US wants relations reset",
          "translated_title": null,
          "link": "https://oc-media.org/kavelashvili-claims-vance-said-us-wants-relations-reset/",
          "date": "Mon, 09 Feb 2026 11:56:21 +0000",
          "category": "political crisis",
          "confidence": 0.1839829981327057,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "18.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Russia offers Armenia ‘comprehensive cooperation’ in nuclear energy ahead of Vance visit",
          "translated_title": null,
          "link": "https://oc-media.org/russia-offers-armenia-comprehensive-cooperation-in-nuclear-energy-ahead-of-vance-visit/",
          "date": "Mon, 09 Feb 2026 11:24:14 +0000",
          "category": "military conflict",
          "confidence": 0.46930059790611267,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "46.9%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Russia tries two Daghestanis in absentia for supporting Ukraine’s Azov Battalion",
          "translated_title": null,
          "link": "https://oc-media.org/russia-tries-two-daghestanis-in-absentia-for-supporting-ukraines-azov-battalion/",
          "date": "Mon, 09 Feb 2026 11:05:02 +0000",
          "category": "military conflict",
          "confidence": 0.47320684790611267,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "47.3%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Review | Some Interviews on Personal Matters — a Georgian woman, uninterrupted",
          "translated_title": null,
          "link": "https://oc-media.org/review-some-interviews-on-personal-matters-a-georgian-woman-uninterrupted/",
          "date": "Mon, 09 Feb 2026 09:23:39 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.2911539673805237,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "29.1%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Monday, 9 February 2026",
          "translated_title": null,
          "link": "https://oc-media.org/monday-9-february-2026/",
          "date": "Mon, 09 Feb 2026 08:29:26 +0000",
          "category": "neutral news",
          "confidence": 0.25396600365638733,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Kulevi Oil Terminal in Georgia May Face EU Sanctions in 20th Russia Package",
          "translated_title": null,
          "link": "https://civil.ge/archives/720691",
          "date": "Tue, 10 Feb 2026 10:51:10 +0000",
          "category": "violent protest",
          "confidence": 0.42772459983825684,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "42.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgia Falls to 50 in TI Corruption Perceptions Index",
          "translated_title": null,
          "link": "https://civil.ge/archives/720698",
          "date": "Tue, 10 Feb 2026 10:09:10 +0000",
          "category": "neutral news",
          "confidence": 0.3959829807281494,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "39.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "GD Scraps Plan to Merge Georgia’s Technical University with Tbilisi State University",
          "translated_title": null,
          "link": "https://civil.ge/archives/720624",
          "date": "Mon, 09 Feb 2026 13:40:56 +0000",
          "category": "violent protest",
          "confidence": 0.23839396238327026,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.8%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        }
      ]
    },
    "Greece": {
      "index": 3.84,
      "raw_score": 11.48,
      "events": [
        {
          "title": "Κ. Τσουκαλάς στο Naftemporiki TV: «Αμφίπλευρη η διεύρυνση του ΠΑΣΟΚ» – Τι είπε για την κόντρα κυβέρνησης-Βενιζέλου",
          "translated_title": "K. Tsoukalas on Naftemporiki TV: \"The expansion of PASOK is two-sided\" - What he said about the opposition to the Venizelos government",
          "link": "https://www.naftemporiki.gr/politics/2070652/k-tsoykalas-sto-naftemporiki-tv-amfipleyri-i-dieyrynsi-toy-pasok-ti-eipe-gia-tin-kontra-kyvernisis-venizeloy/?utm_source=rss&utm_medium=rss&utm_campaign=k-tsoykalas-sto-naftemporiki-tv-amfipleyri-i-dieyrynsi-toy-pasok-ti-eipe-gia-tin-kontra-kyvernisis-venizeloy",
          "date": "Tue, 10 Feb 2026 10:11:07 +0000",
          "category": "political crisis",
          "confidence": 0.9588855504989624,
          "weight": 5.753313302993774,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "95.9%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Greece",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Containerships: Προ των πυλών μεγάλη αύξηση στις διαλύσεις",
          "translated_title": null,
          "link": "https://www.naftemporiki.gr/maritime/2070686/containerships-pro-ton-pylon-megali-ayxisi-stis-dialyseis/?utm_source=rss&utm_medium=rss&utm_campaign=containerships-pro-ton-pylon-megali-ayxisi-stis-dialyseis",
          "date": "Tue, 10 Feb 2026 10:18:59 +0000",
          "category": "violent protest",
          "confidence": 0.6665655374526978,
          "weight": 4.665958762168884,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "66.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Η συγκλονιστική εξομολόγηση του Φαν Ντερ Βιλ",
          "translated_title": null,
          "link": "https://www.naftemporiki.gr/sports/2070715/i-sygklonistiki-exomologisi-toy-fan-nter-vil/?utm_source=rss&utm_medium=rss&utm_campaign=i-sygklonistiki-exomologisi-toy-fan-nter-vil",
          "date": "Tue, 10 Feb 2026 10:39:04 +0000",
          "category": "violent protest",
          "confidence": 0.6589367389678955,
          "weight": 4.6125571727752686,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "65.9%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Βουλή: Άρση ασυλίας του Π. Πολάκη προτείνει η Επιτροπή Δεοντολογίας",
          "translated_title": null,
          "link": "https://www.naftemporiki.gr/politics/2070698/voyli-arsi-asylias-toy-p-polaki-proteinei-i-epitropi-deontologias/?utm_source=rss&utm_medium=rss&utm_campaign=voyli-arsi-asylias-toy-p-polaki-proteinei-i-epitropi-deontologias",
          "date": "Tue, 10 Feb 2026 10:23:43 +0000",
          "category": "political crisis",
          "confidence": 0.6849506497383118,
          "weight": 4.109703898429871,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "68.5%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Ερευνητές του ΜΙΤ δημιούργησαν σκυρόδεμα που λειτουργεί ως… μπαταρία",
          "translated_title": null,
          "link": "https://www.naftemporiki.gr/green/energy/2070712/ereynites-toy-mit-dimioyrgisan-skyrodema-poy-leitoyrgei-os-mpataria/?utm_source=rss&utm_medium=rss&utm_campaign=ereynites-toy-mit-dimioyrgisan-skyrodema-poy-leitoyrgei-os-mpataria",
          "date": "Tue, 10 Feb 2026 11:00:38 +0000",
          "category": "violent protest",
          "confidence": 0.3015618622303009,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "30.2%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "«Κούρσα» εξαγορών στον κλάδο πληροφορικής – Τι φέρνει το Enterprise Software για τους «παίκτες» του ελληνικού οικοσυστήματος",
          "translated_title": null,
          "link": "https://www.naftemporiki.gr/business/2070723/koyrsa-exagoron-ston-klado-pliroforikis-ti-fernei-to-enterprise-software-gia-toys-paiktes-toy-ellinikoy-oikosystimatos/?utm_source=rss&utm_medium=rss&utm_campaign=koyrsa-exagoron-ston-klado-pliroforikis-ti-fernei-to-enterprise-software-gia-toys-paiktes-toy-ellinikoy-oikosystimatos",
          "date": "Tue, 10 Feb 2026 10:54:35 +0000",
          "category": "economic crisis",
          "confidence": 0.36861419677734375,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "36.9%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Σούπερ μάρκετ: Περιορισμένη αύξηση της αξίας και σταθεροποίηση του όγκου των πωλήσεων αναμένουν τα στελέχη για το πρώτο εξάμηνο",
          "translated_title": null,
          "link": "https://www.naftemporiki.gr/finance/economy/2070702/soyper-market-periorismeni-ayxisi-tis-axias-kai-statheropoiisi-toy-ogkoy-ton-poliseon-anamenoyn-ta-stelechi-gia-to-proto-examino/?utm_source=rss&utm_medium=rss&utm_campaign=soyper-market-periorismeni-ayxisi-tis-axias-kai-statheropoiisi-toy-ogkoy-ton-poliseon-anamenoyn-ta-stelechi-gia-to-proto-examino",
          "date": "Tue, 10 Feb 2026 10:45:08 +0000",
          "category": "violent protest",
          "confidence": 0.2720511257648468,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "27.2%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Συνεχίζεται το κρεσέντο παραγγελιών πλοίων από τους Έλληνες εφοπλιστές",
          "translated_title": null,
          "link": "https://www.naftemporiki.gr/maritime/2070711/synechizetai-to-kresento-paraggelion-ploion-apo-toys-ellines-efoplistes/?utm_source=rss&utm_medium=rss&utm_campaign=synechizetai-to-kresento-paraggelion-ploion-apo-toys-ellines-efoplistes",
          "date": "Tue, 10 Feb 2026 10:36:18 +0000",
          "category": "military conflict",
          "confidence": 0.2315518856048584,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.2%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "ΕΛΣΤΑΤ: Με θετικό πρόσημο η βιομηχανική παραγωγή το 2025 – Ο κλάδος με τη μεγαλύτερη άνοδο",
          "translated_title": null,
          "link": "https://www.naftemporiki.gr/finance/economy/2070703/elstat-me-thetiko-prosimo-i-viomichaniki-paragogi-to-2025-o-klados-me-ti-megalyteri-anodo/?utm_source=rss&utm_medium=rss&utm_campaign=elstat-me-thetiko-prosimo-i-viomichaniki-paragogi-to-2025-o-klados-me-ti-megalyteri-anodo",
          "date": "Tue, 10 Feb 2026 10:33:27 +0000",
          "category": "neutral news",
          "confidence": 0.3355344831943512,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "33.6%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Θεσσαλονίκη: Στην «τσιμπίδα» των φορολογικών αρχών αναισθησιολόγος",
          "translated_title": null,
          "link": "https://www.naftemporiki.gr/society/2070710/thessaloniki-stin-tsimpida-ton-forologikon-archon-anaisthisiologos/?utm_source=rss&utm_medium=rss&utm_campaign=thessaloniki-stin-tsimpida-ton-forologikon-archon-anaisthisiologos",
          "date": "Tue, 10 Feb 2026 10:32:25 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.2420022338628769,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.2%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Catherine O’Hara: Από τι πέθανε η αγαπημένη ηθοποιός του «Μόνος Στο Σπίτι»",
          "translated_title": null,
          "link": "https://www.naftemporiki.gr/culture/cinema/2070695/catherine-ohara-apo-ti-pethane-i-agapimeni-ithopoios-toy-monos-sto-spiti/?utm_source=rss&utm_medium=rss&utm_campaign=catherine-ohara-apo-ti-pethane-i-agapimeni-ithopoios-toy-monos-sto-spiti",
          "date": "Tue, 10 Feb 2026 10:30:12 +0000",
          "category": "violent protest",
          "confidence": 0.29667600989341736,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "29.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Coca-Cola HBC: 11.5% increase in operating profits – 19.7% increase in earnings per share",
          "translated_title": null,
          "link": "https://www.naftemporiki.gr/english/2070701/coca-cola-hbc-11-5-increase-in-operating-profits-19-7-increase-in-earnings-per-share/?utm_source=rss&utm_medium=rss&utm_campaign=coca-cola-hbc-11-5-increase-in-operating-profits-19-7-increase-in-earnings-per-share",
          "date": "Tue, 10 Feb 2026 10:25:56 +0000",
          "category": "violent protest",
          "confidence": 0.2980075776576996,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "29.8%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Τι απαντούν τα υπουργεία Οικονομικών και Εργασίας για τα προγράμματα κατάρτισης – «Σε πλήρη συμμόρφωση με το εθνικό και ενωσιακό δίκαιο»",
          "translated_title": null,
          "link": "https://www.naftemporiki.gr/society/2070688/ti-apantoyn-ta-ypoyrgeia-oikonomikon-kai-ergasias-gia-ta-programmata-katartisis-se-pliri-symmorfosi-me-to-ethniko-kai-enosiako-dikaio/?utm_source=rss&utm_medium=rss&utm_campaign=ti-apantoyn-ta-ypoyrgeia-oikonomikon-kai-ergasias-gia-ta-programmata-katartisis-se-pliri-symmorfosi-me-to-ethniko-kai-enosiako-dikaio",
          "date": "Tue, 10 Feb 2026 10:23:16 +0000",
          "category": "violent protest",
          "confidence": 0.31609052419662476,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "31.6%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Snappi: Εγκαινιάζει αποταμιευτικό προϊόν με 1% επιτόκιο",
          "translated_title": null,
          "link": "https://www.naftemporiki.gr/business/2070691/snappi-egkainiazei-apotamieytiko-proion-me-1-epitokio/?utm_source=rss&utm_medium=rss&utm_campaign=snappi-egkainiazei-apotamieytiko-proion-me-1-epitokio",
          "date": "Tue, 10 Feb 2026 10:21:53 +0000",
          "category": "violent protest",
          "confidence": 0.30761152505874634,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "30.8%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Παναθηναϊκός: Θλίψη για την απώλεια της μητέρας του Εργκίν Αταμάν",
          "translated_title": null,
          "link": "https://www.naftemporiki.gr/sports/2070693/panathinaikos-thlipsi-gia-tin-apoleia-tis-miteras-toy-ergkin-ataman/?utm_source=rss&utm_medium=rss&utm_campaign=panathinaikos-thlipsi-gia-tin-apoleia-tis-miteras-toy-ergkin-ataman",
          "date": "Tue, 10 Feb 2026 10:18:16 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.30407413840293884,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "30.4%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        }
      ]
    },
    "Iran": {
      "index": 5.91,
      "raw_score": 47.86,
      "events": [
        {
          "title": "Iran’s top security official in Oman following nuclear talks with US",
          "translated_title": "Iran’s top security official in Oman following nuclear talks with US",
          "link": "https://www.aljazeera.com/news/2026/2/10/irans-top-security-official-in-oman-following-nuclear-talks-with-us?traffic_source=rss",
          "date": "Tue, 10 Feb 2026 07:45:36 +0000",
          "category": "military conflict",
          "confidence": 0.959700882434845,
          "weight": 9.59700882434845,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "96.0%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Iran",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Israel used weapons in Gaza that made thousands of Palestinians evaporate",
          "translated_title": "Israel used weapons in Gaza that made thousands of Palestinians evaporate",
          "link": "https://www.aljazeera.com/features/2026/2/10/israel-used-weapons-in-gaza-that-made-thousands-of-palestinians-evaporate?traffic_source=rss",
          "date": "Tue, 10 Feb 2026 10:31:18 +0000",
          "category": "military conflict",
          "confidence": 0.8849805593490601,
          "weight": 8.8498055934906,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "88.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "LIVE: Pakistan vs USA – T20 World Cup",
          "translated_title": "LIVE: Pakistan vs USA – T20 World Cup",
          "link": "https://www.aljazeera.com/sports/liveblog/2026/2/10/live-pakistan-vs-united-states-t20-world-cup?traffic_source=rss",
          "date": "Tue, 10 Feb 2026 10:30:58 +0000",
          "category": "military conflict",
          "confidence": 0.684910774230957,
          "weight": 6.84910774230957,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "68.5%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Iran",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "US strikes civil nuclear agreement with Armenia, Russia’s former close ally",
          "translated_title": "US strikes civil nuclear agreement with Armenia, Russia’s former close ally",
          "link": "https://www.aljazeera.com/news/2026/2/10/us-strikes-civil-nuclear-agreement-with-armenia-russias-former-close-ally?traffic_source=rss",
          "date": "Tue, 10 Feb 2026 10:06:21 +0000",
          "category": "military conflict",
          "confidence": 0.6683082580566406,
          "weight": 6.683082580566406,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "66.8%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Iran",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Palestinian citizens of Israel demand government do more to stop crime",
          "translated_title": null,
          "link": "https://www.aljazeera.com/news/2026/2/10/palestinian-citizens-israel-demand-government-do-more-stop-crime?traffic_source=rss",
          "date": "Tue, 10 Feb 2026 07:35:28 +0000",
          "category": "political crisis",
          "confidence": 0.742294192314148,
          "weight": 4.453765153884888,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "74.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "The UK’s shrinking centre is Keir Starmer’s real crisis",
          "translated_title": null,
          "link": "https://www.aljazeera.com/opinions/2026/2/10/the-uks-shrinking-centre-is-keir-starmers-real-crisis?traffic_source=rss",
          "date": "Tue, 10 Feb 2026 10:03:41 +0000",
          "category": "political crisis",
          "confidence": 0.7326414585113525,
          "weight": 4.395848751068115,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "73.3%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Humanitarian crisis deepens as South Sudan violence surges",
          "translated_title": null,
          "link": "https://www.aljazeera.com/news/2026/2/10/humanitarian-crisis-deepens-as-south-sudan-violence-surges?traffic_source=rss",
          "date": "Tue, 10 Feb 2026 10:07:12 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.9656773805618286,
          "weight": 2.897032141685486,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "96.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "More than two million people face hunger as drought grips Kenya",
          "translated_title": null,
          "link": "https://www.aljazeera.com/gallery/2026/2/10/severe-drought-leaves-over-two-million-kenyans-hungry-and-desperate?traffic_source=rss",
          "date": "Tue, 10 Feb 2026 09:32:45 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.9285132884979248,
          "weight": 2.7855398654937744,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "92.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "People displaced by South Sudan fighting wait for aid at remote camp",
          "translated_title": null,
          "link": "https://www.aljazeera.com/video/newsfeed/2026/2/10/people-displaced-by-south-sudan-fighting-wait-for-aid-at-remote-camp?traffic_source=rss",
          "date": "Tue, 10 Feb 2026 10:29:24 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.45022761821746826,
          "weight": 1.3506828546524048,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "45.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "How does the cutoff of Starlink terminals affect Russia’s moves in Ukraine?",
          "translated_title": null,
          "link": "https://www.aljazeera.com/news/2026/2/10/how-does-the-cutoff-of-starlink-terminals-affect-russias-moves-in-ukraine?traffic_source=rss",
          "date": "Tue, 10 Feb 2026 08:55:40 +0000",
          "category": "political crisis",
          "confidence": 0.41060981154441833,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "41.1%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Vonn reflects on Winter Olympics downhill crash and tibia injury",
          "translated_title": null,
          "link": "https://www.aljazeera.com/sports/2026/2/10/vonn-reflects-on-winter-olympics-downhill-crash-and-tibia-injury?traffic_source=rss",
          "date": "Tue, 10 Feb 2026 08:12:52 +0000",
          "category": "violent protest",
          "confidence": 0.2813470661640167,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "28.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Ghislaine Maxwell refuses to answer questions from US Congress",
          "translated_title": null,
          "link": "https://www.aljazeera.com/video/newsfeed/2026/2/10/ghislaine-maxwell-refuses-to-answer-questions-from-us-congress?traffic_source=rss",
          "date": "Tue, 10 Feb 2026 08:06:14 +0000",
          "category": "neutral news",
          "confidence": 0.28530266880989075,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "28.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "In Ukraine, deaths from hypothermia rise as Russia attacks energy system",
          "translated_title": null,
          "link": "https://www.aljazeera.com/news/2026/2/10/in-ukraine-deaths-from-hypothermia-rise-as-russia-attacks-energy-system?traffic_source=rss",
          "date": "Tue, 10 Feb 2026 08:05:18 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.7600064873695374,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "76.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "UN spokesman pressed on ‘de facto annexation’ of occupied West Bank",
          "translated_title": null,
          "link": "https://www.aljazeera.com/video/newsfeed/2026/2/10/un-spokesman-pressed-on-de-facto-annexation-of-occupied-west-bank?traffic_source=rss",
          "date": "Tue, 10 Feb 2026 07:57:56 +0000",
          "category": "military conflict",
          "confidence": 0.21681542694568634,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "21.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "‘Evil deeds’: Hong Kong leader praises lengthy jail sentence for Jimmy Lai",
          "translated_title": null,
          "link": "https://www.aljazeera.com/news/2026/2/10/evil-deeds-hong-kong-leader-praises-lengthy-jail-sentence-for-jimmy-lai?traffic_source=rss",
          "date": "Tue, 10 Feb 2026 07:49:31 +0000",
          "category": "neutral news",
          "confidence": 0.3580632209777832,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "35.8%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        }
      ]
    },
    "Iraq": {
      "index": 5.44,
      "raw_score": 34.78,
      "events": [
        {
          "title": "Israeli strike kills four in Gaza City amid West Bank annexation",
          "translated_title": "Israeli strike kills four in Gaza City amid West Bank annexation",
          "link": "https://www.newarab.com/news/israeli-strike-kills-four-gaza-city-amid-west-bank-annexation",
          "date": "Tue, 10 Feb 2026 08:54:17 +0000",
          "category": "military conflict",
          "confidence": 0.9740757942199707,
          "weight": 9.740757942199707,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "97.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Fire at Iraq’s Baiji refinery kills one, injures 13",
          "translated_title": "Fire at Iraq’s Baiji refinery kills one, injures 13",
          "link": "https://www.newarab.com/news/fire-iraqs-baiji-refinery-kills-one-injures-13",
          "date": "Tue, 10 Feb 2026 02:00:54 +0000",
          "category": "military conflict",
          "confidence": 0.8275181651115417,
          "weight": 8.275181651115417,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "82.8%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Iraq",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Prince William meets MbS on visit overshadowed by Epstein row",
          "translated_title": null,
          "link": "https://www.newarab.com/news/prince-william-meets-mbs-visit-overshadowed-epstein-row",
          "date": "Tue, 10 Feb 2026 00:45:56 +0000",
          "category": "political crisis",
          "confidence": 0.929393470287323,
          "weight": 5.576360821723938,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "92.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Former lawyers say NZ mosque shooter planned to confess",
          "translated_title": null,
          "link": "https://www.newarab.com/news/former-lawyers-say-nz-mosque-shooter-planned-confess",
          "date": "Tue, 10 Feb 2026 05:46:41 +0000",
          "category": "terrorist act",
          "confidence": 0.5561801195144653,
          "weight": 5.005621075630188,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "55.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Iran warns Netanyahu US trip could harm diplomacy",
          "translated_title": null,
          "link": "https://www.newarab.com/news/iran-warns-netanyahu-us-trip-could-harm-diplomacy",
          "date": "Tue, 10 Feb 2026 09:58:49 +0000",
          "category": "political crisis",
          "confidence": 0.7197774052619934,
          "weight": 4.3186644315719604,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "72.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Palestinian woman hospitalized after seizure in US ICE detention",
          "translated_title": null,
          "link": "https://www.newarab.com/news/palestinian-woman-hospitalized-after-seizure-us-ice-detention",
          "date": "Tue, 10 Feb 2026 02:41:38 +0000",
          "category": "violent protest",
          "confidence": 0.48124292492866516,
          "weight": 3.368700474500656,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "48.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Prince William to meet footballers, gamers in Saudi Arabia",
          "translated_title": null,
          "link": "https://www.newarab.com/news/prince-william-meet-footballers-gamers-saudi-arabia",
          "date": "Tue, 10 Feb 2026 10:27:42 +0000",
          "category": "neutral news",
          "confidence": 0.2895120680332184,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "29.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Netanyahu meeting with Trump to push for broader Iran deal",
          "translated_title": null,
          "link": "https://www.newarab.com/news/netanyahu-meeting-trump-push-broader-iran-deal",
          "date": "Tue, 10 Feb 2026 09:23:40 +0000",
          "category": "political crisis",
          "confidence": 0.319511741399765,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "32.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Draw means Al-Hilal drop first points in Asian Champions League",
          "translated_title": null,
          "link": "https://www.newarab.com/news/draw-means-al-hilal-drop-first-points-asian-champions-league",
          "date": "Tue, 10 Feb 2026 05:37:17 +0000",
          "category": "neutral news",
          "confidence": 0.30857589840888977,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "30.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Lebanon building collapse toll rises to 14",
          "translated_title": null,
          "link": "https://www.newarab.com/news/lebanon-building-collapse-toll-rises-14",
          "date": "Tue, 10 Feb 2026 05:30:38 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.17163430154323578,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "17.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Top Iran security official to travel to Oman",
          "translated_title": null,
          "link": "https://www.newarab.com/news/top-iran-security-official-travel-oman",
          "date": "Tue, 10 Feb 2026 05:09:24 +0000",
          "category": "violent protest",
          "confidence": 0.23790273070335388,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Immigration judge rejects Trump effort to deport Tufts student",
          "translated_title": null,
          "link": "https://www.newarab.com/news/immigration-judge-rejects-trump-effort-deport-tufts-student",
          "date": "Tue, 10 Feb 2026 03:30:33 +0000",
          "category": "neutral news",
          "confidence": 0.3542332053184509,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "35.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Saudi Arabia wealth fund set to announce strategy revamp",
          "translated_title": null,
          "link": "https://www.newarab.com/news/saudi-arabia-wealth-fund-set-announce-strategy-revamp",
          "date": "Tue, 10 Feb 2026 01:31:04 +0000",
          "category": "military conflict",
          "confidence": 0.20812009274959564,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "20.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "International outrage grows over Israel's plans for West Bank",
          "translated_title": null,
          "link": "https://www.newarab.com/news/international-outrage-grows-over-israels-plans-west-bank",
          "date": "Tue, 10 Feb 2026 00:08:55 +0000",
          "category": "political crisis",
          "confidence": 0.3879161477088928,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "38.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Is US envoy Tom Barrack a peacemaker for the Middle East?",
          "translated_title": null,
          "link": "https://www.newarab.com/opinion/us-envoy-tom-barrack-peacemaker-middle-east",
          "date": "Tue, 10 Feb 2026 10:32:35 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.7535992860794067,
          "weight": -1.5071985721588135,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "75.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        }
      ]
    },
    "Syria": {
      "index": 5.83,
      "raw_score": 45.4,
      "events": [
        {
          "title": "What will it take for Syrians to return to Aleppo after years of war? - Al Jazeera",
          "translated_title": "What will it take for Syrians to return to Aleppo after years of war? - Al Jazeera",
          "link": "https://news.google.com/rss/articles/CBMiswFBVV95cUxNZU8weGdFVXMzbDhlc3VBOThwMGxBWU5FX3lfNG9HM3JLSk9POEQyWkJRSEdpMzBiZTJ5eFlzZUxybkZBaTFoZEQtc2RlaEM0NGFmVnpFaHpTMzVRczhyVXFSbUtPMWRSM2ZmTXBZdGJVb05tTWdCMnJ0NVZOWlhpTnF3cXR0N2xHWWFsdWlQemQ2eHE4emRqWE9rUm56SW4tTjNITjNNZ2VPaW45bkw2SnY4MNIBuAFBVV95cUxOZlByUHR5MHZUUjc2X0pvT0F5MHpPbFFFd0owNWV6UjZHMlhiZ0JPaHRjS29kbTBaMHE3bEpYR24zTHFJNFM0cjVqeVhaV2ZxbFJ0aTFrdGJFbEJzM0JiWE5mZDlya3I2QVBveVRTMW5MYWp4YkFpelUxYnI3S3pBYmh0aTl0dWJ6RHRyMTVBQ1FxYUZlNmRIdFhscVZhMzNYSHdsS0NLZm4tZVhjWTltdjJuNWdWVVUy?oc=5",
          "date": "Tue, 10 Feb 2026 05:06:39 GMT",
          "category": "military conflict",
          "confidence": 0.9395579099655151,
          "weight": 9.395579099655151,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "94.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "US Forces Transfer IS Prisoners from Syria to Iraq by Buses - Military.com",
          "translated_title": "US Forces Transfer IS Prisoners from Syria to Iraq by Buses - Military.com",
          "link": "https://news.google.com/rss/articles/CBMiggFBVV95cUxPYjh3UDN1U1FEQjh0Ul9ZclZ0RFdjck5reURoNUY1MTFWYU5RTmVqQXBvQWNRSC1aaG9wMUYxRjhTck1VZXM4T0o2em1uVmFhV0FtdXRKaThhV0ZlOHBOZXo1UE9ILXkxUHJIZ2t5TWJGczY5V3Y2eHM3U3ppcnNfQUpB?oc=5",
          "date": "Mon, 09 Feb 2026 13:49:18 GMT",
          "category": "military conflict",
          "confidence": 0.807503879070282,
          "weight": 8.07503879070282,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "80.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "IDF Destroys Jamaa Islamiya Weapons Depot In Southern Syria | LIVE BLOG - i24NEWS",
          "translated_title": "IDF Destroys Jamaa Islamiya Weapons Depot In Southern Syria | LIVE BLOG - i24NEWS",
          "link": "https://news.google.com/rss/articles/CBMivAFBVV95cUxObE50UWxtdWhMMzZ0MjZ5eTdVVHIwdEVJZXQ5ZEYzU0hWY3R0UHpfbldEMnlBWjFZOElCWmxhYlNQVHRmaWxkc1JpcmV2bklFU1ctR092U1hDRUh4UEJrbEFQYV9kbnViWlJFWHpwVUFGZ29OSVE1eURtVVkweFZSNFdzMFFRV0dsZWtJaXNqbGJhSzJRaXQ4Q0diSmZDd2NzRXdXQTFMY3F0eWw4WG4zT1V5VHNubW5Sdm5sag?oc=5",
          "date": "Tue, 10 Feb 2026 06:49:00 GMT",
          "category": "military conflict",
          "confidence": 0.7667647004127502,
          "weight": 7.667647004127502,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "76.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Turkey's army chief says 'no plans to withdraw' from Syria - AL-Monitor",
          "translated_title": "Turkey's army chief says 'no plans to withdraw' from Syria - AL-Monitor",
          "link": "https://news.google.com/rss/articles/CBMilwFBVV95cUxNR2RvQnh6ZFJkdlAyX1JHWHU2WWpKSzZ2ay02eTRuT3BQRkhwdVQzNGRGVk5Qc2hDR19GTEItSU9rMTJzMExRbV9TOWV2ZUVHY21OTjZIV0c0eG1iM0RhSjk1c1VNeFdxVmZpNmpoeDg2X29wMXh4T1ExYUFQRWdBQVR3dnJPQ3VZVy15a0ZpU1dDUDRYcWhn?oc=5",
          "date": "Mon, 09 Feb 2026 17:01:22 GMT",
          "category": "military conflict",
          "confidence": 0.6893121600151062,
          "weight": 6.893121600151062,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "68.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Iraq security risks rise as ISIS detainees move from Syria - The Jerusalem Post",
          "translated_title": "Iraq security risks rise as ISIS detainees move from Syria - The Jerusalem Post",
          "link": "https://news.google.com/rss/articles/CBMiXEFVX3lxTE5TRlpOZHBTNC1zY1ZpWHpJd2RmZXNKeEtydy1HWmJrclJwQ1M4RGluTzZJbWotN2JrTnVZSkdJSlVfU09vZ3NISklpUDhkSUR3eFdWMFVEcUt3T1hf?oc=5",
          "date": "Mon, 09 Feb 2026 17:21:35 GMT",
          "category": "military conflict",
          "confidence": 0.5905627608299255,
          "weight": 5.905627608299255,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "59.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Can Syria break its sectarian cycle? The Kurdish experiment was doomed - UnHerd",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMicEFVX3lxTFBLR016YmtGVlBmdldsa3N6cG9nd3ZPUHd5SVdWNWRhR01nWGQxb3B3VTVfUHpTeW5JbTV3NFpjclc3NUNURGRtSGs5RHFVSGdQdmR5b1FUZFVBZTlGcGhISVkwMmFjdXo1UGxoYklCRVg?oc=5",
          "date": "Tue, 10 Feb 2026 00:07:59 GMT",
          "category": "political crisis",
          "confidence": 0.7516916990280151,
          "weight": 4.510150194168091,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "75.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Sex crazed Bashar al-Assad had lover arrange wives of his officers, spent hours playing Candy Crush - WION",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi3gFBVV95cUxNczl5WHhxMmFYSXVBQ1RIcE0yWFE4QklmOUZiZEdlR2RBSmgwS0IyTzBJRXpxdE00NE5jakI3QkllQ3doSUQtU3g3WTZCYkt2UXlTYXJkRUtZTDAtNDlFUmlhQTZ3amFwY3lxMEJuaktRTjlGbVh1T1dyQTA2Qks2NU1uWm1OVjZOSVhYTWMtRlJJLUVyOTVNSkU4RXZ4YXBTRnl3b2FNdXVzS08xQzkzRTZaLW5PTDc3MFpoQUpOaTF4enJYV2gwTEU5RHBUcFNyRW91Rno0V3RfZjRRY1HSAeMBQVVfeXFMTkVmOHUzbFFGZTV0dUZIcjBnd1A0dy1EUHlXeEthN09BQjlfRUxJZFN5YkgwMktWR0lRa29qT2ZnZkk2T3QtVzFkemFaM0YxS3VDOWdIb3Y4MzdPempMekZzYVBkSFRpVVNoeGxXcm5HMUZ3VUVwNjF4RmNraTBzTlktYU44bmlSTVpHV1pjS29EQWpJclpzN1lEbGZ5dW85WEIzeGx2QjFkLVhCcDdDYVd5QnRneWd3RjVjNm12VGdYamNsZmplaERJTklEWjI3cmYtdG81aU4xNG1uNjgyNXNKX3c?oc=5",
          "date": "Tue, 10 Feb 2026 04:53:00 GMT",
          "category": "political crisis",
          "confidence": 0.4926508665084839,
          "weight": 2.9559051990509033,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "49.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Eating Kosher in the Heart of Syria: Lamb-Stuffed Zucchini but Hold the Yogurt - The New York Times",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMihAFBVV95cUxPaXNITHdhQm02ZnN5Z3gtc3ZqTHF3ZnBCZTdIYWx3U1RyWWRWRHJxeFJELTNiSEdxSkZlQWxPSFFyWXh6MUdYUnpqTnBYUzExLUVNNElXQjRYMDNqeXdhaDZSUHBPRzdQTjVuMksyajFlNkEweEZOelNhbjZ2YkctemszNng?oc=5",
          "date": "Tue, 10 Feb 2026 10:00:45 GMT",
          "category": "neutral news",
          "confidence": 0.6739853024482727,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "67.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "flynas Plans New Airline in One of the Most Dangerous Countries in the World - Aviation A2Z",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMihgFBVV95cUxQZXFmZXN4dWtBeTh2Q0Y2UHg1ZHpaUnNWVFUzVVdEMWhqV0xVZXhXWm41dGlKSlhXQm5xOU9wTU9aaFpma3RJZFRCeWFwX3BoVVE0X1BtTnRzN0VxV0RTZTh5cjBmY2FSRUMtZzlKNE5RTGc2ZlRiMERZWTNjOWpyd0JkWFdjUQ?oc=5",
          "date": "Mon, 09 Feb 2026 12:04:00 GMT",
          "category": "humanitarian crisis",
          "confidence": 0.20598383247852325,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "20.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Flynas Syria airline set to launch in fourth quarter 2026 - سانا",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiSEFVX3lxTE5DdzVHWXdfcm41VVdnSzRaOXV0ZnNvMGhxSGpXVWp2QUliWkNBaFBLUU4xT205b25WSGRhVWctdTV3SEs4dHJKVQ?oc=5",
          "date": "Mon, 09 Feb 2026 07:54:03 GMT",
          "category": "violent protest",
          "confidence": 0.24889592826366425,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.9%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Flynas to Launch New Airline in Syria - Construction Business News Middle East",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMigAFBVV95cUxPRnBWNHpVN3VwWFUtSWNRTFd6T004Q1E1ekZPMDhFNXhKMDFtQWtEeWlYanpSZm1ncFFzMGhsUGZtTE91ZFg2cDE0SEFTLXhQOTlMR2NVeGN3MVA0QTFTXzFRdENIVDhBem01dVdKN0RhMWxpbGlneVVibmk4SlNTXw?oc=5",
          "date": "Mon, 09 Feb 2026 07:58:13 GMT",
          "category": "military conflict",
          "confidence": 0.41403335332870483,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "41.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria steps into leadership role after Riyadh anti-ISIS meeting - Yahoo",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMijgFBVV95cUxQVXFMeWg0bHNZeEZfYXhFdTBDRkpWZE4xS181Y3Via3dwdzZYWm9Ub2VXcGJNWVg2Nmd5T3VuUi1VZC1OQmlWenZDS191Yjdjc3NISksyak1LQzZiM1hESXdTX1hERXd1X3paaU1pX3lzV1RXNXByNElKSk1zRWJqZ0pkTUhCNl90ZE1Wc1h3?oc=5",
          "date": "Tue, 10 Feb 2026 09:39:59 GMT",
          "category": "military conflict",
          "confidence": 0.32276415824890137,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "32.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "A Topography of the Violence in New Syria - Homeland Security Today",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMipgFBVV95cUxQQUl6Sk5XUFFTbE9yRFRYNGFjTVVucmxxYnV0TE9zMXp6bUs4ZWhZUnQ3ZGwza01xX2NQdXhvOGtyMkV1aHQ0Y2JjZ0dtN21lZkdOTXZiUUZkU3FrTkhSTzRUZVpTLWh0cEx1cFI2Q20tN1JRR1dGVzJkVFg5WjBlNmgxTE1RQ2NaNTEzcmNjWE1kTENWU1JZdzhENHdob3RNT1FnazhR?oc=5",
          "date": "Tue, 10 Feb 2026 09:54:22 GMT",
          "category": "military conflict",
          "confidence": 0.4283474385738373,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "42.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Opinion: Breakdown of ISIS detention centres in Syria poses serious threat to Canada - National Post",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMirAFBVV95cUxNekJteG9jSTJZQW8td2pSOVVhM0Z4bUFiM0RjVU1UVl9DZnc2THVaazkzcUkydVp4Y2lKVEhTeXVSb2FSLW5zN0Jsc2hNNlU2Z1RNQkdUUGZvVVJZMWZzbkFNa0tLU1VCbTQweXRoWEpfUTJtLVotNU5NQjVWamZlWFR2dWFfdkpLbXJ1bS1tN3VvUmp1bnk3X0ZyY2dUR2ZLRm5BeTBqVVNTZXhY?oc=5",
          "date": "Mon, 09 Feb 2026 11:05:37 GMT",
          "category": "terrorist act",
          "confidence": 0.5004764795303345,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "50.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria’s new equation | Daily Sabah - Daily Sabah",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMibEFVX3lxTE00dmZNbHFxOTdjelo2NGhXRkpXVUo5eVcweHdQZEhpRUNnaHZSdGt0MGFXNE9aR3lpZHhoTTRwWm9tdXkzLUFvUHc3ejhOR1VLbThrZHctUnlnNm5lME9HRGJuZTZydENPUGRQYdIBckFVX3lxTE1ZSm4wUVROQzFxYnVhQzM3dm5RaVFSVnp4UU5fWlo2M0JTQkNaS3VDLV83MGU0cUktUG9vR2h0RnJ6LUNtemJubFQxZlFlMnI5UlIwOFV4R3h0YXB2clVJLWJEOGpiUi1jVXFiV05XUDFkZw?oc=5",
          "date": "Mon, 09 Feb 2026 12:35:00 GMT",
          "category": "political crisis",
          "confidence": 0.38198375701904297,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "38.2%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        }
      ]
    },
    "Bulgaria": {
      "index": 2.2,
      "raw_score": 3.26,
      "events": [
        {
          "title": "Bulgaria men's national team coach, Iliyan Vasilev, passes away - ihf.info",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMioAFBVV95cUxPaFVDVEk4NXBjNHQtYzJveGZ1UzJqbWp3Z2dfOXEwLWNMakJNd2xjNWtXa1JRVVp2ckNhVkFYc3BLLUl1VzdVd3BodmthTmpTTWsxRXpyN1JNUGpJMHZTWW1BUFJfbllzN0I4ekFOZUI2NkhkYmdQckpOcEUxNC1QUnlWOE9URXpjQmZVbEVtVWdUU2x1NVREWkNjdFhPR3lY?oc=5",
          "date": "Mon, 09 Feb 2026 17:50:29 GMT",
          "category": "violent protest",
          "confidence": 0.46576663851737976,
          "weight": 3.2603664696216583,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "46.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Cluster of mystery deaths in western Bulgarian mountains confounds police - Reuters",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMirgFBVV95cUxOY3lkV3Jtd0pjcWhOTkJJa0xBQl9FbDUtdDMyOUsyWWRBRjAyWV8wSE5kRnl0eGZhakdTeEsyTFVIRU9seFlTNjBSMlBPb1IzVjZLeTRIdmZkU2dRT1VuWEhLdE4wTTBqc0xBSXJKMEVnWVBjRURTU3NuLTFOSHcxQzN4TFh1cVRMeUtLQV95VkFGaU1Vc3BWY1VXc3ZYMEJZLVAwYXJ6MmhyZTg2Y1E?oc=5",
          "date": "Mon, 09 Feb 2026 18:29:00 GMT",
          "category": "humanitarian crisis",
          "confidence": 0.23171722888946533,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Mystery Grips Bulgaria Over Two Triple Killings in Mountains - Balkan Insight",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMinwFBVV95cUxOa2hLT2JGU3BXemdGU1RqdHdtVmkxRldBM1ptcVlpaldfQmYySnJTM3llV0JDWnd6Z05pblBZT1U2WDFTc0tWYzRRanNXLUJOMWdyanl4SGs5Z2dYOTVFRzhDSFI4VFpybHE0TTlKSkZka0w3OFk0ZVVGQ29YdXQ5cDZUOUtzUkZTRm5nSXg2empON1E1X3VoREltVWJJSkk?oc=5",
          "date": "Mon, 09 Feb 2026 13:14:43 GMT",
          "category": "military conflict",
          "confidence": 0.26753875613212585,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "26.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Triple murder mystery likened to TV show \"Twin Peaks\" by prosecutor after 3 suspects found dead in Bulgaria - cbsnews.com",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMijgFBVV95cUxPakpRMzNpblBnZkxiY0xvcl9LSzZpVWFNcEppVXhIUjVjT2oydTh2VnJpU2V4dzVUbnY1UzBrczM1TkRNQi01WGZyaVdRaFVnUkMxT1JieTloS1RHWUxuMkdCbzVMQjY3MThOYXVBcXZwdHVtQjhWT1Q2ZzlIYUNfUkZvYXlWN0lLMUt0Tmhn0gGTAUFVX3lxTE4xd3Y5QVd3WEtWaTBoOXNUU2t2NTlBZEhleElGRXpoeUlkRW9qaUE3UERYSmFKaDBGT1RRRzVaUWUybnZFZHJrQ3JsM0pOQml6b3NnWnFSbUhIaTdwRFFXZF8zZ0FmUmhkazRDR1FoZWE1WXI1dGhCcTlTeVhIME5lT2hqdXhXMDRTWFdaN1FIcUN5OA?oc=5",
          "date": "Mon, 09 Feb 2026 11:44:00 GMT",
          "category": "terrorist act",
          "confidence": 0.35817626118659973,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "35.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria v Belgium: Gille and Vliegen clinch winning point - daviscup.com",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMilAFBVV95cUxPUzEzSlNZcHNWTEdZNl9JRnptVERTODBvUUtVSF9GRG54aUZKajVmM0dlZ01ET1ZVN1N0V0tVdldfdFlGR2E2VGF6MUFuNzh3S1d6TnN6b2JYTG85X3huYl9aTzFZanY4dHhHZ0lJOC1kZVdkNUtTdkQ0YmZyY3dybldsNWJadUZxQzdLRkJwbDItQ1My?oc=5",
          "date": "Sun, 08 Feb 2026 13:59:25 GMT",
          "category": "violent protest",
          "confidence": 0.2854759097099304,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "28.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "France Overtakes Hungary, Germany, Italy, Romania, Bulgaria, Spain, And Several Other Countries In Europe In Reigning Over Safe And Secure Tourism, Attracting Global Guests With Its Bold Fusion Of Luxury, Adventure, And Unbeatable Hospitality: What Y - Travel And Tour World",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi3wJBVV95cUxPb0U1eGxrOFNtT3RGT3U0VXdHRzNTOVA3WHljRHJFRGpoUjVnZV9QSUZLOTV0VXNFa3pTQWx6eXNTVkRmYzc2dHFFVEdEaDdlTEp2LW03R1Y3VDlsQXpwWDRFRTc4UWJQWXNlRGJpTVNTWFQxcjVUOVVmaFBkSVAzQk02ejBJT2tzOXFrajlCdV9RbUdPYktzZV9yZnZHdkNEcnpUaE11Unc5Uks3MXdDbVJNZWhkXzY0UUxvc09yYW1KMFl3OGJZbkxBWFRhT3NqVFJGOW5qRmxEQTZvNjVOYm5EZzZoaFdPbEo5RDF5UGdTR2dfNVczOVlELVN3Z0RjbnhqQmxKMEFZTVlTeWQ1NGgwa3N2SzRhenc2cjdsNUVzeWdzT1lGWmFYLTg2SkdiNFNpLXU4UC1Mbkk1UTAtVS1tdVJTZ21PVHU3SlV2blVDWEZOVEwxNFpsOXpqZlk?oc=5",
          "date": "Mon, 09 Feb 2026 05:40:08 GMT",
          "category": "violent protest",
          "confidence": 0.2666986286640167,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "26.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Winter Weather Tightens Grip on Bulgaria on February 10 - Novinite.com - Sofia News Agency",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMinAFBVV95cUxOMklZNzBQbTVLMnUyMXEwYTM4MVQxdE8yVTVrYUdqaVM3MllTaGVhX3V5cC1MMzdZVi1sd3p3UzR5T2wxYl9KZVVtVExKbDU4NnFuTG9fN1Q5TlN3NE1ERXVXUWJsOFhvS3ZWQ08xdTV1WGFZZHdYei1uZXVIM19mMVpmcHNob1RsYjlqYlZ3Uk1kdzV1ZXZkNlVGbGY?oc=5",
          "date": "Mon, 09 Feb 2026 15:09:20 GMT",
          "category": "neutral news",
          "confidence": 0.20732739567756653,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "20.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "'Twin Peaks': Mystery mountain deaths in Bulgaria baffle police - Yahoo",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiiwFBVV95cUxQeWFTN1cyU0lfTkhnXzVCYUx3eGtMd0ZzbkZ1UHh4U1poLXNBdHJKdWQzS0ZYMnlDZWZFbWhMeDFKSkVjNnloMk5nUFQxWXRWYzB4UmRHajFKYlEtWDRXMzZlcjVrYS13VE1MbDJ5eWVHb3NsSkppWm1oWXQyRWV2dEdpS3RjUFZBenNj?oc=5",
          "date": "Tue, 10 Feb 2026 04:08:00 GMT",
          "category": "humanitarian crisis",
          "confidence": 0.20822370052337646,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "20.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Canada Joins Italy, Finland, Portugal, Turkey, United Kingdom, Bulgaria, And More Than Eighty-Five Countries In Facing Stricter Travel Entry Requirements As Saudi Arabia Overhauls E-Visa Process - Travel And Tour World",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi2AJBVV95cUxOdXZKeHBaMFRwdDZVbnFJN0NSQ1VoSUYyNXA2QXlWT1NZNjZIY0RVZE9XTXVxX2hCbFpaQU5OckJ2cnBpbGFEWlpuSFJ3Sk5Rd1JaVWdaeldadXFHa0FiNjZTYllDRi1BQ1lNLTBVRjd2THdmQXg4eE1ScjJ5UGRRYUdCRkFuYTBVOWZVZ2RvUUUxWjd2OUZZVTc1bmxYT1Nmd0ZUTGY3c25zeS1EbVlaYVNqeDhtVEsyVklWLTUxWkZfZDRxeE11VHlIc3YyUDRiYjlSQm1zY2dKVWhLX0I0S01oYWxlMTRlOVFFV0J2NGwyTXVPMENld2p6QTBoTUNRa3pId1BYM0l1NFFCb015eDRwOU5XRlRlODh4Y1BNWnpTVFl2d2NZaExUbmJBU1FPaDFPMVVibmtkZlp0S2NfaTZSQWdtQk5pREIybHZpMW5TUVZJVTdxbg?oc=5",
          "date": "Mon, 09 Feb 2026 10:25:46 GMT",
          "category": "political crisis",
          "confidence": 0.16656051576137543,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "16.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Tervel Zamfirov Wins Historic Medal for Bulgaria at the Winter Olympics - Novinite.com - Sofia News Agency",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMisgFBVV95cUxOaHhSWEF4aU0tQVUtS0RMSjY5emgyMkxRTzdELU55bW5MWFlJd0VxS3piUmp0TDlDTE1VSnYxRVpwUGZFeHVpY0tNRGw0eGpwQ2V5VmpjbGZCeFF2bF9QRjBabVlKUkRVNWFDTXdZR0RTT0dBSmFpR1BWU0o2LVhZTGk2WWg0TW1salM2ODZlRV9hS0gzU1E3Z3U0LXhwUkZBTjQ3aEVLSXpQZGlpamRNT3BB?oc=5",
          "date": "Sun, 08 Feb 2026 14:08:38 GMT",
          "category": "violent protest",
          "confidence": 0.36219000816345215,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "36.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Activists Claim Discovery of Russian Paramilitary Site in Bulgarian Village - Novinite.com - Sofia News Agency",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMitwFBVV95cUxPZF9mRF9QQ3dSSkFrOU5nS0U4VkJwVTU4S0tiNDh3MzE3LTNId09KNHRLRThIVFBURUh6cUF5R21xbVUwdEZDNzFFcS1EVUlwVVFkSkZFQ2U5MWttUV9RRC1pUG9kcFZPNnFYbmZWbm5ZdnZYU09Wbm1uR003V0lGSk1yRGt4MnNXdzBwaDUwemZMLUcxSGdwcVlSM293UjdQMXU3aWJleGUzOUNxZGZZWFVTMmR4b1k?oc=5",
          "date": "Mon, 09 Feb 2026 09:12:59 GMT",
          "category": "political crisis",
          "confidence": 0.20417460799217224,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "20.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria wins first Winter Olympics medal in 20 years with snowboarding podium - WCNC",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxPSXZ6cHlLdmJweW83X2JINXpjS00wVFJOc0RWcHFIVDNEazc5bjVtMVlyNEtDTDlubTdyWjN6eU9xanpuLWFaYWdXTy1EZjhOeUxSOVl4bHpZVWlobktHLWl5WV9MNUt5MlBqS3dlUWs0SDBvTXhoQjRIbEZBbFNUbE9TUEMxNVRQbk9tYkNDYmpDaG9VQjM2LXotTmh1RHoyWGVubXE0OHpaU0kxOFhxVFcyUDBqUHdlZ2FKQnpDTWJhWGRQYnNnUDYtNGxWV2V1b3Ywelhn?oc=5",
          "date": "Mon, 09 Feb 2026 23:23:00 GMT",
          "category": "violent protest",
          "confidence": 0.3307036757469177,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "33.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria Industrial Output Continues to Fall - TradingView",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMimwFBVV95cUxNM0NsWkI3MXMyU3ZMenZtZTRnN3VEY2pjOE5HT1hFaF9xVHJ2TXVFMWdScXJ4SkYzUlJSTURrQWxNek5NRk02bHZUYVRJYTlxNER0cDRPQzhNbkpDbFBpOVplSDJJREpNbVA3eHI1SE9MUno3WlU4cFRMd1BhUEdVdHdfbGRPTTN2QTdHMlFDRS1mbFJzVDZQU3lBaw?oc=5",
          "date": "Tue, 10 Feb 2026 09:20:56 GMT",
          "category": "terrorist act",
          "confidence": 0.2731682360172272,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "27.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria sells 150 mln euro of ten-year T-notes at 3.84% yield - SeeNews",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMipAFBVV95cUxPWEZfQm9lWUlLeFo3S2JTYlRpRmxXaGdwemtIUXpoanp5R3BkNzQyUFNrRUstZVp5UC1nbmc4SlJocjc1WmM2bUpTejFnTzA1Slp5dFBna3R6V2FSN3diTVMwdV9PYlJCQVg3STFmUnRyR2ZUVExtMnBCdWVNa1ZSdzdwazFCUFZFcE45RVJMbHdINWtrdEpQenNJSzNnVzdiejRIeQ?oc=5",
          "date": "Tue, 10 Feb 2026 10:03:23 GMT",
          "category": "violent protest",
          "confidence": 0.3116876482963562,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "31.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "UK–Bulgaria partnership aims to strengthen semiconductor innovation and supply chains - New Electronics",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiywFBVV95cUxOZ0JRZDBXZjc1cmJObkRJYWFGU21iOWxhaHM2VlhTSTR0TElybUhJTk1KUXREcERsdFdBYTA1VklEN3MwS19IcTRldVNQUERxTmloSkpYanBsaWp5SGJEOW83b3BOYk9MZEdHWlZMNWVYSTQ1dE9MVmhHY1gxNDhVaXNfR0hsRWZsYTcwREVhSDN2WDM2eUZzRDlLNGoxZlUzeXdKTGR6OFRRZkVMa2c3aW10TU5MN2JmTUZVN0xhdV9wVHhIZzVJTERaWQ?oc=5",
          "date": "Tue, 10 Feb 2026 06:09:52 GMT",
          "category": "violent protest",
          "confidence": 0.3737535774707794,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "37.4%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        }
      ]
    }
  },
  "history": [
    {
      "timestamp": "2026-02-08T11:44:16.679894",
      "main_index": 7.92,
      "index": 7.92,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-08T13:17:09.398506",
      "main_index": 7.3,
      "index": 7.3,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-08T14:50:03.184580",
      "main_index": 7.77,
      "index": 7.77,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-08T15:46:39.408278",
      "main_index": 7.52,
      "index": 7.52,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-08T16:52:43.795496",
      "main_index": 7.5,
      "index": 7.5,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-08T17:54:04.466686",
      "main_index": 6.94,
      "index": 6.94,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-08T19:00:02.790486",
      "main_index": 7.01,
      "index": 7.01,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-08T19:51:29.336103",
      "main_index": 7.21,
      "index": 7.21,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-08T20:54:25.893331",
      "main_index": 7.02,
      "index": 7.02,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-08T21:47:15.382544",
      "main_index": 7.21,
      "index": 7.21,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-08T22:48:16.871786",
      "main_index": 6.98,
      "index": 6.98,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-08T23:57:07.875739",
      "main_index": 7.69,
      "index": 7.69,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-09T03:00:18.379300",
      "main_index": 7.48,
      "index": 7.48,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-09T05:23:41.010725",
      "main_index": 7.21,
      "index": 7.21,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-09T07:26:37.531020",
      "main_index": 7.18,
      "index": 7.18,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-09T09:17:36.026298",
      "main_index": 7.07,
      "index": 7.07,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-09T11:14:37.249336",
      "main_index": 7.4,
      "index": 7.4,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-09T12:11:20.297084",
      "main_index": 6.87,
      "index": 6.87,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-09T13:39:21.135085",
      "main_index": 7.3,
      "index": 7.3,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-09T15:13:39.693335",
      "main_index": 7.55,
      "index": 7.55,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-09T16:19:32.054127",
      "main_index": 7.71,
      "index": 7.71,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-09T18:09:53.177918",
      "main_index": 7.09,
      "index": 7.09,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-09T19:38:26.955248",
      "main_index": 7.06,
      "index": 7.06,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-09T21:11:33.902180",
      "main_index": 7.43,
      "index": 7.43,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-09T21:59:04.045558",
      "main_index": 7.61,
      "index": 7.61,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-09T23:09:12.841924",
      "main_index": 7.71,
      "index": 7.71,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-09T23:58:07.954478",
      "main_index": 7.76,
      "index": 7.76,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-10T03:07:07.839884",
      "main_index": 7.62,
      "index": 7.62,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-10T05:27:18.374344",
      "main_index": 7.73,
      "index": 7.73,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-10T07:28:01.926520",
      "main_index": 7.95,
      "index": 7.95,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-10T09:17:44.334965",
      "main_index": 8.21,
      "index": 8.21,
      "type": "historical"
    },
    {
      "timestamp": "2026-02-10T11:14:20.773216",
      "main_index": 7.85,
      "index": 7.85,
      "type": "historical"
    }
  ],
  "forecast": [
    {
      "timestamp": "2026-02-10T12:14:20.773216",
      "index": 7.88,
      "main_index": 7.88,
      "confidence": 0.45,
      "type": "forecast"
    },
    {
      "timestamp": "2026-02-10T13:14:20.773216",
      "index": 7.91,
      "main_index": 7.91,
      "confidence": 0.42,
      "type": "forecast"
    },
    {
      "timestamp": "2026-02-10T14:14:20.773216",
      "index": 7.95,
      "main_index": 7.95,
      "confidence": 0.38,
      "type": "forecast"
    },
    {
      "timestamp": "2026-02-10T15:14:20.773216",
      "index": 7.98,
      "main_index": 7.98,
      "confidence": 0.34,
      "type": "forecast"
    },
    {
      "timestamp": "2026-02-10T16:14:20.773216",
      "index": 8.02,
      "main_index": 8.02,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-02-10T17:14:20.773216",
      "index": 8.05,
      "main_index": 8.05,
      "confidence": 0.3,
      "type": "forecast"
    }
  ],
  "methodology": {
    "name": "Modified Goldstein Scale",
    "description": "AI-powered threat classification using XLM-RoBERTa multilingual model with category-weighted scoring",
    "weights": {
      "military conflict": 10.0,
      "terrorist act": 9.0,
      "violent protest": 7.0,
      "political crisis": 6.0,
      "economic crisis": 4.0,
      "humanitarian crisis": 3.0,
      "peaceful diplomacy": -2.0,
      "neutral news": 0.0
    },
    "formula": "ThreatIndex = log10(1 + sum(category_weight * confidence)) * 3.5",
    "scale": {
      "min": 1.0,
      "max": 10.0,
      "thresholds": {
        "STABLE": [
          1.0,
          4.0
        ],
        "ELEVATED": [
          4.0,
          7.0
        ],
        "CRITICAL": [
          7.0,
          10.0
        ]
      }
    }
  }
};