window.BNTI_DATA = {
  "meta": {
    "generated_at": "2026-05-19T08:24:34.437266",
    "main_index": 5.26,
    "status": "ELEVATED",
    "active_scan": false,
    "next_update": "2026-05-19T10:00:00",
    "version": "2.0.0"
  },
  "countries": {
    "Armenia": {
      "index": 6.11,
      "raw_score": 3.5,
      "events": [
        {
          "title": "Leak reveals secret documents on Russia’s hybrid attacks against Armenia",
          "translated_title": "Leak reveals secret documents on Russia’s hybrid attacks against Armenia",
          "link": "https://jam-news.net/leak-reveals-secret-documents-on-russias-hybrid-attacks-against-armenia/",
          "date": "Mon, 18 May 2026 16:31:57 +0000",
          "source_country": "Georgia",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Leaked docs on Russian hybrid attacks against Armenia",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Armenia",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Criminal proceedings launched over video containing threats against Armenian PM",
          "translated_title": "Criminal proceedings launched over video containing threats against Armenian PM",
          "link": "https://en.armradio.am/2026/05/18/criminal-proceedings-launched-over-video-containing-threats-against-armenian-pm/",
          "date": "Mon, 18 May 2026 12:38:21 +0000",
          "source_country": "Armenia",
          "category": "terrorism",
          "weight": 7.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Threats against Armenian PM",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "CIS to deploy 120 observers for Armenia’s parliamentary elections",
          "translated_title": "CIS to deploy 120 observers for Armenia’s parliamentary elections",
          "link": "https://en.armradio.am/2026/05/18/cis-to-deploy-120-observers-for-armenias-parliamentary-elections/",
          "date": "Mon, 18 May 2026 11:12:18 +0000",
          "source_country": "Armenia",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Armenian parliamentary elections monitoring",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Armenia",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "CIS to Send 120 Election Observers to Armenia",
          "translated_title": "CIS to Send 120 Election Observers to Armenia",
          "link": "https://hetq.am/en/article/181463",
          "date": "Mon, 18 May 2026 16:37:00 +0400",
          "source_country": "Armenia",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "CIS sends 120 election observers to Armenia",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Catholicos Aram I raises Artsakh, Christian unity and Lebanon issues in private meeting with Pope Leo XIV",
          "translated_title": null,
          "link": "https://en.armradio.am/2026/05/18/catholicos-aram-i-raises-artsakh-christian-unity-and-lebanon-issues-in-private-meeting-with-pope-leo-xiv/",
          "date": "Mon, 18 May 2026 13:08:37 +0000",
          "source_country": "Armenia",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Catholicos Aram I discusses Artsakh and Lebanon with the Pope",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Armenian Ambassador to Greece discusses cooperation with Hermes Institute",
          "translated_title": null,
          "link": "https://en.armradio.am/2026/05/18/armenian-ambassador-to-greece-discusses-cooperation-with-hermes-institute/",
          "date": "Mon, 18 May 2026 12:23:54 +0000",
          "source_country": "Armenia",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Armenian-Greek cooperation",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Lithuanian FM to visit Armenia",
          "translated_title": null,
          "link": "https://en.armradio.am/2026/05/18/lithuanian-fm-to-visit-armenia/",
          "date": "Mon, 18 May 2026 09:52:27 +0000",
          "source_country": "Armenia",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Lithuanian-Armenian relations",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Unibank Launches Fee-Free Online Payroll Card Issuance",
          "translated_title": null,
          "link": "https://hetq.am/en/article/181464",
          "date": "Mon, 18 May 2026 16:42:00 +0400",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Unibank launches fee‑free online payroll card",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Yerevan begins preparations for COP17 Biodiversity Summit",
          "translated_title": null,
          "link": "https://en.armradio.am/2026/05/18/yerevan-begins-preparations-for-cop17-biodiversity-summit/",
          "date": "Mon, 18 May 2026 13:27:04 +0000",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Yerevan prepares for COP17 biodiversity summit",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        }
      ]
    },
    "Georgia": {
      "index": 4.27,
      "raw_score": 1.88,
      "events": [
        {
          "title": "‘A woman’s body is not the state’s demographic resource or the Church’s property’: Comment from Tbilisi",
          "translated_title": "‘A woman’s body is not the state’s demographic resource or the Church’s property’: Comment from Tbilisi",
          "link": "https://jam-news.net/a-womans-body-is-not-the-states-demographic-resource-or-the-churchs-property-comment-from-tbilisi/",
          "date": "Mon, 18 May 2026 17:04:40 +0000",
          "source_country": "Georgia",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Critique of state demographic policies",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Georgia",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "‘You cannot build happiness on abortion’: New Georgian patriarch’s first sermon on family and demographics",
          "translated_title": "‘You cannot build happiness on abortion’: New Georgian patriarch’s first sermon on family and demographics",
          "link": "https://jam-news.net/you-cannot-build-happiness-on-abortion-new-georgian-patriarchs-first-sermon-on-family-and-demographics/",
          "date": "Mon, 18 May 2026 16:47:36 +0000",
          "source_country": "Georgia",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Patriarch's sermon opposing abortion",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Georgia",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Georgia to create agency to monitor ‘aggressive communication in public spaces’",
          "translated_title": "Georgia to create agency to monitor ‘aggressive communication in public spaces’",
          "link": "https://jam-news.net/georgia-to-create-agency-to-monitor-aggressive-communication-in-public-spaces/",
          "date": "Mon, 18 May 2026 15:07:30 +0000",
          "source_country": "Georgia",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Georgia to create agency monitoring aggressive public communication",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Georgia",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Two Illegally Detained Georgian Citizens Released From Tskhinvali Custody",
          "translated_title": null,
          "link": "https://civil.ge/archives/734905",
          "date": "Mon, 18 May 2026 12:56:15 +0000",
          "source_country": "Georgia",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "release of detained Georgian citizens from Tskhinvali",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Gunba Says Abkhazia’s International Recognition, UN Membership ‘Inevitable’",
          "translated_title": null,
          "link": "https://civil.ge/archives/734849",
          "date": "Mon, 18 May 2026 11:12:31 +0000",
          "source_country": "Georgia",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Abkhazia's anticipated international recognition",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgia to Establish Interior Ministry Unit to ‘Systematically Monitor’ ‘Hate Speech’ in Public Spaces",
          "translated_title": null,
          "link": "https://civil.ge/archives/734811",
          "date": "Mon, 18 May 2026 10:22:55 +0000",
          "source_country": "Georgia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "new unit to monitor hate speech in public spaces",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Money Transfers to Georgia Up 7.6% in April, Led by EU and U.S.",
          "translated_title": null,
          "link": "https://civil.ge/archives/734821",
          "date": "Mon, 18 May 2026 08:47:21 +0000",
          "source_country": "Georgia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "rise in money transfers to Georgia",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgia, Azerbaijan Sign Energy, Transport Agreements After Kobakhidze-Aliyev Meeting in Baku",
          "translated_title": null,
          "link": "https://civil.ge/archives/734813",
          "date": "Mon, 18 May 2026 14:14:29 +0000",
          "source_country": "Georgia",
          "category": "trade_agreement",
          "weight": -2.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "energy and transport agreements with Azerbaijan",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        }
      ]
    },
    "Greece": {
      "index": 5.06,
      "raw_score": 2.5,
      "events": [
        {
          "title": "Protesters rally in Athens after Israeli interception of Gaza flotilla",
          "translated_title": null,
          "link": "https://www.middleeasteye.net/live-blog/live-blog-update/protesters-rally-athens-after-israeli-interception-gaza-flotilla",
          "date": "Tue, 19 May 2026 06:15:17 +0100",
          "source_country": "Iran",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Greece",
          "llm_final_country": "Greece",
          "llm_subject": "Athens protests Israeli interception of Gaza flotilla",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Greece"
        }
      ]
    },
    "Iran": {
      "index": 6.16,
      "raw_score": 3.55,
      "events": [
        {
          "title": "Η Τεχεράνη ετοιμάζεται για σύντομες αλλά υψηλής έντασης συγκρούσεις, απειλεί τον Κόλπο και τα θαλάσσια περάσματα",
          "translated_title": "Tehran prepares for short but high-intensity clashes, threatens Gulf and sea passages",
          "link": "https://www.protothema.gr/world/article/1820937/i-teherani-etoimazetai-gia-sudomes-alla-upsilis-edasis-sugrouseis-apeilei-ton-kolpo-kai-ta-thalassia-perasmata/?utm_source=rss",
          "date": "Tue, 19 May 2026 10:12:00 +0300",
          "source_country": "Greece",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Iranian military buildup",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Iran",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Iran arrests over 4,000 on charges related to war: rights group",
          "translated_title": "Iran arrests over 4,000 on charges related to war: rights group",
          "link": "https://www.newarab.com/news/iran-arrests-over-4000-charges-related-war-rights-group",
          "date": "Mon, 18 May 2026 20:23:35 +0100",
          "source_country": "Iraq",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Iran mass arrests related to war",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Iran court to hear case against director Panahi after return",
          "translated_title": null,
          "link": "https://www.newarab.com/news/iran-court-hear-case-against-director-panahi-after-return",
          "date": "Mon, 18 May 2026 20:23:28 +0100",
          "source_country": "Iraq",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Iran court case against director Panahi",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Iran’s revolution was not destined to end in clerical rule",
          "translated_title": null,
          "link": "https://www.newarab.com/opinion/irans-revolution-was-not-destined-end-clerical-rule",
          "date": "Mon, 18 May 2026 15:42:09 +0100",
          "source_country": "Iraq",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Future of Iran's revolutionary system",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "'This may be the last time you hear my voice': Political executions surge in Iran since start of war",
          "translated_title": null,
          "link": "https://www.bbc.com/news/articles/cn8p392nl7yo?at_medium=RSS&at_campaign=rss",
          "date": "Sun, 17 May 2026 23:02:56 GMT",
          "source_country": "Iran",
          "category": "humanitarian_crisis",
          "weight": 3.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Political executions surge in Iran since start of war",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Trump says he called off new Iran attack at request of Gulf states",
          "translated_title": null,
          "link": "https://www.bbc.com/news/articles/c7079e55zjro?at_medium=RSS&at_campaign=rss",
          "date": "Mon, 18 May 2026 22:30:58 GMT",
          "source_country": "Iran",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "IRRELEVANT",
          "llm_final_country": "Iran",
          "llm_subject": "Trump says he called off Iran attack at Gulf states request",
          "llm_country_audit_corrected": true,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Trump warns 'clock is ticking' for Iran as peace progress stalls",
          "translated_title": null,
          "link": "https://www.bbc.com/news/articles/cd0p4y9y48xo?at_medium=RSS&at_campaign=rss",
          "date": "Mon, 18 May 2026 09:58:35 GMT",
          "source_country": "Iran",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "IRRELEVANT",
          "llm_final_country": "Iran",
          "llm_subject": "Trump warns clock is ticking for Iran as peace stalls",
          "llm_country_audit_corrected": true,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Iran says US behaviour undermining diplomatic efforts",
          "translated_title": null,
          "link": "https://www.middleeasteye.net/live-blog/live-blog-update/iran-says-us-behaviour-undermining-diplomatic-efforts",
          "date": "Tue, 19 May 2026 07:03:08 +0100",
          "source_country": "Iran",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Iran accuses US of undermining diplomacy",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Trump says attack on Iran 'on hold' as negotiations ongoing",
          "translated_title": null,
          "link": "https://www.newarab.com/news/trump-says-attack-iran-hold-negotiations-ongoing",
          "date": "Tue, 19 May 2026 07:07:09 +0100",
          "source_country": "Iraq",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "US attack on Iran paused for negotiations",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Trump says new Iran attack 'on hold' as Gulf states intervene",
          "translated_title": null,
          "link": "https://www.newarab.com/news/trump-says-new-iran-attack-hold-gulf-states-intervene",
          "date": "Tue, 19 May 2026 02:46:59 +0100",
          "source_country": "Iraq",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Gulf states intervene to prevent Iran attack",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        }
      ]
    },
    "Iraq": {
      "index": 5.06,
      "raw_score": 2.5,
      "events": [
        {
          "title": "Why is US General David Petraeus visiting Baghdad?",
          "translated_title": null,
          "link": "https://www.newarab.com/news/why-us-general-david-petraeus-visiting-baghdad",
          "date": "Mon, 18 May 2026 15:15:15 +0100",
          "source_country": "Iraq",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iraq",
          "llm_final_country": "Iraq",
          "llm_subject": "US General Petraeus visit to Baghdad",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        }
      ]
    },
    "Syria": {
      "index": 6.55,
      "raw_score": 4.0,
      "events": [
        {
          "title": "Israeli patrol conducts raid, house searches in southern Quneitra countryside",
          "translated_title": "Israeli patrol conducts raid, house searches in southern Quneitra countryside",
          "link": "https://npasyria.com/en/137804/",
          "date": "Mon, 18 May 2026 09:43:37 +0000",
          "source_country": "Syria",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Israeli raid in Quneitra countryside",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "The Muhajirin: Inside Syria's uneasy pact with foreign fighters",
          "translated_title": "The Muhajirin: Inside Syria's uneasy pact with foreign fighters",
          "link": "https://www.newarab.com/analysis/muhajirin-inside-syrias-uneasy-pact-foreign-fighters",
          "date": "Mon, 18 May 2026 17:26:51 +0100",
          "source_country": "Iraq",
          "category": "terrorism",
          "weight": 7.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syria's pact with foreign fighters",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "ISIS Seeks a ‘New Phase of Fighting’ in Syria - The Media Line",
          "translated_title": "ISIS Seeks a ‘New Phase of Fighting’ in Syria - The Media Line",
          "link": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxNalE0SS1xTDRjZUZ4ZUhkaUx4Ujh0MGIycHdEOVIyUXhHVkxmb19CRl9PeVNKc28tS0M1OFVzaXY5NjRvaHl4UHpDR0NLVkw3NjJ3V1laU3lpTzlwbU8tc1VybHVac1RPYV9EQU9ILWVreW9aczN2aENmdmtpTVY3VjRDMzRHVDJz?oc=5",
          "date": "Mon, 18 May 2026 22:27:35 GMT",
          "source_country": "Syria",
          "category": "terrorism",
          "weight": 7.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "ISIS plans new fighting phase in Syria",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Syria",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Syrian Interior Ministry member killed in Suwayda blast",
          "translated_title": "Syrian Interior Ministry member killed in Suwayda blast",
          "link": "https://npasyria.com/en/137816/",
          "date": "Mon, 18 May 2026 19:24:21 +0000",
          "source_country": "Syria",
          "category": "terrorism",
          "weight": 7.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Interior Ministry member killed in Suwayda blast",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "First Afrin IDP convoy leaves Kobani",
          "translated_title": "First Afrin IDP convoy leaves Kobani",
          "link": "https://npasyria.com/en/137820/",
          "date": "Tue, 19 May 2026 06:05:52 +0000",
          "source_country": "Syria",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "IDP convoy departs Kobani",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "First transit convoy crosses Syria from Turkey toward Iraq",
          "translated_title": "First transit convoy crosses Syria from Turkey toward Iraq",
          "link": "https://npasyria.com/en/137813/",
          "date": "Mon, 18 May 2026 12:43:48 +0000",
          "source_country": "Syria",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Transit convoy crosses Syria toward Iraq",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Kurds hand over Kobani administration to Syrian government",
          "translated_title": null,
          "link": "https://www.newarab.com/news/kurds-hand-over-kobani-administration-syrian-government",
          "date": "Mon, 18 May 2026 17:39:13 +0100",
          "source_country": "Iraq",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Kurds transfer Kobani administration to Syrian government",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syrian Writer: No democracy without citizenship, law, Just constitution - ANHA",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMimAFBVV95cUxPcm9oenRlZkthTlpFZTR6MVFUY29feTlXc1owUktpNXIxQ0F2Z0t0azU3eUxHMkVyV29uWHE0cGtUVVctSXo4T1lzYk5wRUxvXzRxdTJVa1B6WHNhX1FJdV81THlxR3JGc002ZzdFXzYxQkZIaXBNeFJZRU1Fck9jeVRRS2lhSE5QM3pyLVdkZzVwUmpYS2RCdw?oc=5",
          "date": "Tue, 19 May 2026 02:20:48 GMT",
          "source_country": "Syria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syrian writer calls for democratic reforms",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "How Syrian Kurds became privileged minority in new Syrian system - Türkiye Today",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMirgFBVV95cUxNX1NEeWxGLVFscUZCWnI5OENjWGlBUHdvU0Z0U0VwSDZfMnpPYnl4bW9LSTZyX3dURnhhZE1jQ2tiZmlEMG9fZjBTWFRYWGZPcS15dkI0a0p6OHBkZG01Uk9XRjNKcFh1MmJzMVVRc1BPMXNwelRGbm1raEFyVUpqX29SOGxFUUtQNWp6di1reDhSbGxtTE1ORm9RZHJCVVNqMGpfRk9KZHVoLU9QUUE?oc=5",
          "date": "Mon, 18 May 2026 08:38:56 GMT",
          "source_country": "Syria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syrian Kurds' privileged status in new system",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "2,000 women gather in Kobanê: We will determine our own future in Syria - ANF | Articles",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMisAFBVV95cUxOQ3Z4WHNXQUVMck8xSnJjcEJ3ZXQySmUxbnQ3RFktTDFwQzFwU1o0Yl94amx3NFRnLVR4Vkx3cXctRnlFZlY0TkZ6T1hKempISWFSX1BFM2JLTU9HNzZJZjN5TGo2Unh1aVpRdnZ5Ri1oRnhSZ09xMmQyZnZxMW1yVDgxTVZsQW5XVzg4QkNkcm02NFJSbWVPdlNmSGJjRkJDZGtMSm5fRFNVRjZkV1JubQ?oc=5",
          "date": "Mon, 18 May 2026 06:35:04 GMT",
          "source_country": "Syria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "women protest for self-determination in Kobanê",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "EU extends sanctions on former Assad regime for one year",
          "translated_title": null,
          "link": "https://www.newarab.com/news/eu-extends-sanctions-former-assad-regime-one-year",
          "date": "Mon, 18 May 2026 20:23:32 +0100",
          "source_country": "Iraq",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "EU sanctions on former Syrian regime",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria: Council renews restrictive measures targeting the former al-Assad regime for one year and de-lists certain entities - consilium.europa.eu",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMimAJBVV95cUxNSUdPTThRVmphUDQ2YWpKUFR3aS1iTFpBM2U5UnJLRHdPSGlqSnN4WG0wUDJJYkRWLVduUzUtLWZWM1hRaHlGc2ZhOGExN2hvU1RCdHAzMnl4T3BzbDNGZ21OUGRWR2twTzFGNmI2Z01seXZ2a2NLdzRHOFVZRkpyN0p3YW5mUDljZkpQNnVBQnJHVzlSRkxYb2lLX1ExLW1GMkgwVk5SRENQOXFjeHZUUFR0QkFHVTRVSGZpSkNERWp1bU9UMEVCcktGbHRXbmlYRXBGRFBxeE94V0FQSDNIZVp5OU82eEk1dWVrb2pkRWs3Uzlud2dETlhRV2paeTRxZ0liMWJXdnc4UEpsN0xqRzJZa2VsRDls?oc=5",
          "date": "Mon, 18 May 2026 10:22:52 GMT",
          "source_country": "Syria",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "EU renews sanctions on Syrian regime",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Blocked Strait of Hormuz Leads to New Opportunities for Syria - The New York Times",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMinwFBVV95cUxQLVJDM0lLdTdyT3phMWhHZ19PbDRXTk4teEVPRmdBblZCU1FxTHNKVWVHV3RMOGhQMTEzaHV2ZWl0LV9EQ09FS2pZbzRXZ21UdldmRVZKZklLakNFUEZDRVhQUWRNSFJ4bW5lY3FET3FsMk1nQlFmb01wdk9odjM1elV0dlhvaXJSVk01VFF3ZHczRG0zWHFaOG1mb0lTWU0?oc=5",
          "date": "Mon, 18 May 2026 09:55:24 GMT",
          "source_country": "Syria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syria benefits from Strait of Hormuz blockage",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syrian President al-Sharaa vows to close displacement camps by 2027 - Türkiye Today",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMisAFBVV95cUxPSTBVUWpBSEZSTkRmOWtLbzhmX0ZDQWROY05oRzNwT3ZsM2RnSnQ5QWJ3RTgySXROOWV6QnUwVlM2dk1sTlo0UEY4MXR5V2RISFRSR0ZQOVJobHc1RmdQUk9JU0x5YWpYXzg4cXhRYVgwamFFTXZvRklYU1Y3LUV2ZjN0LW9FSzlHcE5QY3h3NXdDVkktOEw3Q2NlZ1ZIa1UyZ1hneWZZczRVSUFKdU9MTg?oc=5",
          "date": "Mon, 18 May 2026 13:52:32 GMT",
          "source_country": "Syria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "closing displacement camps",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria to take part in G7 financial talks in Paris on Monday - L'Orient Today",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMisgFBVV95cUxPcGlUa3U4V0Z4S2RxQkxZV3VWR2YzbDVwN0xaMG1CR29SRXZGVmtJWVMxcDNDdlZFTk5oS29BSkRfVGJCZFFjazNjWWFSWWZoNlduSC15UlRZbDgyUTlHVUgxWm1NeDZEc2JQX0c4QkYxbkE5aUdrd2JwUzdxTHVvZmRGRVZXeWk1N0NaaEJyTzRjVEI5bjh1Mm1lUzhUVmd5eDI2cHFXWTNFQWFfSjQyOGtn?oc=5",
          "date": "Mon, 18 May 2026 11:28:22 GMT",
          "source_country": "Syria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syria joins G7 financial talks",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        }
      ]
    },
    "Bulgaria": {
      "index": 1.0,
      "raw_score": 0.0,
      "events": [
        {
          "title": "No, Bulgaria’s New Premier Isn’t Pro-Kremlin - Jacobin",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMid0FVX3lxTE85LUF3WnBFSF9KdGFSUE5SQmdjZXFCdlE0WExaN2p1TmxoWWhrTWZlTHJJb05vbE5BZnVlcjVHR21pWmVmVU1aTGdQekpxaGFOM3JBc1c1YnpwY2pjSkRwdDlUQ3lUT3lHY01ZVmoxTjZVd2ZGZWRv?oc=5",
          "date": "Sun, 17 May 2026 13:02:50 GMT",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Analysis of Bulgaria's new premier stance",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria cheers Dara's 'Bangaranga' and country's first Eurovision win - USA Today",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMitgFBVV95cUxQNmYyMC1FQmRPZ3RONjhwN1pITEdmZTl6WVNGekg4WVE5bkNUank4c1k4UEloOVNjcWJobWtvcVdVMTBvNG1Wb3VzUnhDbWNzVFhYZVFBTDJWTklaX1B4OGhXWjI5VzlIempTYU9Qc2NjbnFKWXRxd2wwQUdvLXIwbExJVnJNVG4xQUVDYm00YTZkTnJNTmhTTmNHZ0J3ZHFCQnhSWkt3WEVCT09TaGJWSG9UcFcwUQ?oc=5",
          "date": "Sun, 17 May 2026 16:57:00 GMT",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Bulgaria celebrates first Eurovision win",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria wins Eurovision Song Contest for the first time - Georgia Today",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMickFVX3lxTE5CN2JFa0N3bEtIeE56Zlo1ak9uVjhNTGEzX1puTkZleGRXaFdNS3pGSEtUdHVPMnBfVkVfOVJoN0lUY3k3d29YOHBMVzVrT0FoR0dTTXRHdE4tY2hVcVBVd1M0a25hQ1NMdERFWlAxUEIzUQ?oc=5",
          "date": "Sun, 17 May 2026 08:43:11 GMT",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Bulgaria wins Eurovision Song Contest",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria president to address World Urban Forum in Baku - The Nation (Pakistan )",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMikAFBVV95cUxPOUpCLUFfZU1YMXdLeFFETmU2RXAzQ1lUSGJxc0NXbnQ4Smg5eFRXR1FTemQxNFdjM054MnNWR0VpQkZmZzhiemNyM08xUGdZODJuTGEzbnBXOFNlaWs4Z19TaWI4QXg0WmlHbkV5WkY3TXRPOVZSVVktbVdDV005X2hnUFdIZFZQZWZnQk5Rd3M?oc=5",
          "date": "Tue, 19 May 2026 02:30:00 GMT",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Bulgarian president to speak at World Urban Forum",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Two Greeks Behind Bulgaria's Eurovision 2026 Victory - Greek City Times",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMilAFBVV95cUxNWEZudmIxd1NPSlNUbFVFTVNlaHB5TGJJV1RFRDJBSEEwS0pZU2FQZmNsU2tyZzYyM3A5aEVlbUowR2hzV0VFMklEZGlVWHhnR1l4eG5PWEV0UU9VS1UtcjIyaG1SYTZRUEE5bmpyQjlqVUVFckhCcU1mSVlmdkhuSDNBR295ZExULW9ta1psUVpXaHVi?oc=5",
          "date": "Sun, 17 May 2026 23:08:07 GMT",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Greek contributors to Bulgaria's Eurovision victory",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria wins the 70th Eurovision Song Contest with 'Bangaranga' - USA Today",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMitAFBVV95cUxOaFJndl9vbzRzR2NOa1NoSzliRWhpOTFfUnM1VFh1TXJrTmdGMGx1LUc4WDJPa3ZUN0JWTGhvcmJ0Wm1DSkt2M2RkOE9KenpkMkdnMXVYU1RwbXlxRS1obVR4dWxhZGt3dC1QNWg5QVZhNHdpVnhib2x6cTRvMWhJcWdiT2xDamQ1UFBLUE5lYjgwNE9CLVhuTWRiNXc1Sld2WEZmNWFCNXozNlFqVGQ2c3gzejM?oc=5",
          "date": "Sun, 17 May 2026 16:39:11 GMT",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Bulgaria wins 70th Eurovision with 'Bangaranga'",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "70th edition: Bulgaria's Eurovision winner flies home to rapturous welcome - RTL Today",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMirgFBVV95cUxNV21Ma2ppTDhDcldoeERfVzNSbUtpZXpXLUljVTIyck1tcHpUU3FXV0QyMGtod2F4OWZOMTc5dEFCYWRfT1JBUFItcExCTzMzZXlCQzFxVHROR01WbC1uNG1PZ1FwVGRvLTRQUUU4UmduSGNDWUowMnltZk9WbWN5VUd2TnBZb0xaREdwYVM3M01IY3Y3c0xlM1JrNVFqblFyT2JDOU5UY0lUdWhsc0E?oc=5",
          "date": "Sun, 17 May 2026 20:57:08 GMT",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Eurovision winner receives warm welcome in Bulgaria",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "70th edition: Bulgaria's 'Bangaranga' wins Eurovision, with Israel second - RTL Today",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMidEFVX3lxTE5DOEVVZ19MTUJoV2NuYk1kQUFYQ2l5dHdPREtaYlYxNDA4Y1JEUVp5c1pVNTd4ZmVBVUs4WHhjcUFrNjdGSEthMDlqaGFHN0I1V0M3c1QzWURqeFBMenJOQ29lMDhacVNMSXBwN2ltSzlmWTNz?oc=5",
          "date": "Mon, 18 May 2026 06:17:06 GMT",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Bulgaria's 'Bangaranga' wins Eurovision, Israel second",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Шефът на общинския съвет предлага DARA да бъде обявена за почетен гражданин на София",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/bulgaria/2026/05/19/4915744_shefut_na_obshtinskiia_suvet_predlaga_dara_da_bude/?ref=rss",
          "date": "Tue, 19 May 2026 10:37:00 +0300",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Sofia mayor proposes DARA as honorary citizen",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Случаите на морбили вече са близо 300",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/zdrave/2026/05/19/4915743_sluchaite_na_morbili_veche_sa_blizo_300/?ref=rss",
          "date": "Tue, 19 May 2026 10:37:00 +0300",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Mumps cases approach 300 in Bulgaria",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        }
      ]
    }
  },
  "history": [
    {
      "timestamp": "2026-05-17T09:46:22.194521",
      "main_index": 4.71,
      "index": 4.71,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-17T11:18:57.013226",
      "main_index": 3.25,
      "index": 3.25,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-17T13:21:52.173962",
      "main_index": 3.23,
      "index": 3.23,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-17T15:11:03.296691",
      "main_index": 3.45,
      "index": 3.45,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-17T17:09:45.448895",
      "main_index": 3.85,
      "index": 3.85,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-17T19:19:53.396301",
      "main_index": 4.76,
      "index": 4.76,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-17T23:18:10.518306",
      "main_index": 5.16,
      "index": 5.16,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-18T12:04:21.044910",
      "main_index": 4.77,
      "index": 4.77,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-18T15:26:46.889755",
      "main_index": 4.57,
      "index": 4.57,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-18T18:22:01.143048",
      "main_index": 5.26,
      "index": 5.26,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-18T20:11:43.446736",
      "main_index": 3.34,
      "index": 3.34,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-18T21:35:07.278488",
      "main_index": 4.68,
      "index": 4.68,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-19T08:24:34.436482",
      "main_index": 5.26,
      "index": 5.26,
      "type": "historical"
    }
  ],
  "forecast": [
    {
      "timestamp": "2026-05-19T09:24:34.436482",
      "index": 5.01,
      "main_index": 5.01,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-05-19T10:24:34.436482",
      "index": 5.11,
      "main_index": 5.11,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-05-19T11:24:34.436482",
      "index": 5.21,
      "main_index": 5.21,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-05-19T12:24:34.436482",
      "index": 5.31,
      "main_index": 5.31,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-05-19T13:24:34.436482",
      "index": 5.4,
      "main_index": 5.4,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-05-19T14:24:34.436482",
      "index": 5.5,
      "main_index": 5.5,
      "confidence": 0.3,
      "type": "forecast"
    }
  ],
  "methodology": {
    "name": "LLM Border Threat Taxonomy",
    "description": "OpenRouter free routing chooses the final country attribution and canonical threat category for each headline.",
    "weights": {
      "military_conflict": 8.0,
      "terrorism": 7.0,
      "border_security": 5.0,
      "political_instability": 4.0,
      "humanitarian_crisis": 3.0,
      "diplomatic_tensions": 2.5,
      "trade_agreement": -2.0,
      "neutral": 0.0
    },
    "formula": "PerCountry = 1 + 9*(1 - exp(-avg(weight)/5 * 1.2)); Composite = weighted_avg(PerCountry)",
    "scale": {
      "min": 1.0,
      "max": 10.0,
      "thresholds": {
        "STABLE": [
          1.0,
          4.0
        ],
        "ELEVATED": [
          4.0,
          7.0
        ],
        "CRITICAL": [
          7.0,
          10.0
        ]
      }
    }
  },
  "briefing": {
    "regional_summary_6h": {
      "slot_start": "2026-05-19T00:00:00Z",
      "slot_end": "2026-05-19T06:00:00Z",
      "generated_at": "2026-05-19T08:24:11Z",
      "next_refresh_at": "2026-05-19T12:00:00Z",
      "window_hours": 6,
      "source_event_count": 2,
      "source_countries": [
        "Iran",
        "Syria"
      ],
      "headline": "Iranian attack plans stalled amid Gulf diplomatic push, Syrian rhetoric fuels internal uncertainty",
      "bullets": [
        "Iranian plans for a new attack were reportedly paused after Gulf states intervened, according to statements attributed to former US President Trump.",
        "In Syria, a writer's public call for citizenship‑based democracy underscored ongoing political instability.",
        "No cross‑border troop movements, militant clashes, or border‑security incidents were recorded in the six‑hour window."
      ],
      "watch": null
    }
  }
};