window.BNTI_DATA = {
  "meta": {
    "generated_at": "2026-05-01T22:59:16.478903",
    "main_index": 4.56,
    "status": "ELEVATED",
    "active_scan": false,
    "next_update": "2026-05-02T00:00:00",
    "version": "2.0.0"
  },
  "countries": {
    "Armenia": {
      "index": 2.55,
      "raw_score": 0.79,
      "events": [
        {
          "title": "Armenia arrests two Russian nationals over alleged money smuggling",
          "translated_title": "Armenia arrests two Russian nationals over alleged money smuggling",
          "link": "https://oc-media.org/armenia-arrests-two-russian-nationals-over-alleged-money-smuggling/",
          "date": "Fri, 01 May 2026 13:17:38 +0000",
          "source_country": "Georgia",
          "category": "border_security",
          "weight": 5.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "arrests for alleged money smuggling",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Pashinyan Says Armenia Must Finance Trump’s “Board of Peace”",
          "translated_title": null,
          "link": "https://hetq.am/en/article/181143",
          "date": "Thu, 30 Apr 2026 16:05:00 +0400",
          "source_country": "Armenia",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Pashinyan on financing Trump peace board",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Yerevan Marks May Day: Corporate Sponsors Take Centerstage",
          "translated_title": null,
          "link": "https://hetq.am/en/article/181163",
          "date": "Fri, 01 May 2026 22:20:00 +0400",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "May Day corporate sponsorship in Yerevan",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Pashinyan on May Day: Praises Taxpaying Workers, Says Nothing on Labor Movement",
          "translated_title": null,
          "link": "https://hetq.am/en/article/181161",
          "date": "Fri, 01 May 2026 16:36:00 +0400",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Pashinyan May Day labor remarks",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Pashinyan Marks May Day: “Long Live Work and Education&quot;",
          "translated_title": null,
          "link": "https://hetq.am/en/article/181162",
          "date": "Fri, 01 May 2026 15:39:00 +0400",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Pashinyan May Day work and education message",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Excavations at Armenia’s Arakelots Monastery: One of Europe’s Seven Most Endangered Monuments",
          "translated_title": null,
          "link": "https://hetq.am/en/article/181141",
          "date": "Fri, 01 May 2026 12:07:00 +0400",
          "source_country": "Armenia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Arakelots Monastery excavation and heritage status",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Russia blocks the second batch of Armenian Jermuk water, affecting 1.1 million bottles",
          "translated_title": null,
          "link": "https://oc-media.org/russia-blocks-the-second-batch-of-armenian-jermuk-water-affecting-1-1-million-bottles/",
          "date": "Fri, 01 May 2026 10:28:38 +0000",
          "source_country": "Georgia",
          "category": "trade_agreement",
          "weight": -2.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Armenia",
          "llm_subject": "Russian blockage of Armenian water exports",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        }
      ]
    },
    "Georgia": {
      "index": 5.87,
      "raw_score": 3.25,
      "events": [
        {
          "title": "Georgian police briefly detain two in farmers protest in Marneuli",
          "translated_title": "Georgian police briefly detain two in farmers protest in Marneuli",
          "link": "https://oc-media.org/georgian-police-briefly-detain-two-in-farmers-protest-in-marneuli/",
          "date": "Thu, 30 Apr 2026 13:26:55 +0000",
          "source_country": "Georgia",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "Georgian police detention of protesting farmers",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgian Dream claims ties with US will improve in May",
          "translated_title": null,
          "link": "https://oc-media.org/georgian-dream-claims-ties-with-us-will-improve-in-may/",
          "date": "Fri, 01 May 2026 14:19:40 +0000",
          "source_country": "Georgia",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Georgia",
          "llm_final_country": "Georgia",
          "llm_subject": "expected improvement in US‑Georgia relations",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        }
      ]
    },
    "Greece": {
      "index": 1.0,
      "raw_score": 0.0,
      "events": []
    },
    "Iran": {
      "index": 5.39,
      "raw_score": 2.79,
      "events": [
        {
          "title": "Тръмп обяви ударите в Иран за \"прекъснати\", но може да ги поднови без разрешение",
          "translated_title": "Trump has declared strikes on Iran \"suspended\" but may resume them without authorization",
          "link": "https://www.dnevnik.bg/sviat/2026/05/01/4909594_trump_obiavi_udarite_v_iran_za_prekusnati_no_moje_da/?ref=rss",
          "date": "Fri, 01 May 2026 23:15:00 +0300",
          "source_country": "Bulgaria",
          "category": "military_conflict",
          "weight": 8.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Trump announces Iran strikes suspended, may renew unilaterally",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Iran",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Iranian Nobel laureate Narges Mohammadi hospitalised as health deteriorates",
          "translated_title": "Iranian Nobel laureate Narges Mohammadi hospitalised as health deteriorates",
          "link": "https://www.aljazeera.com/news/2026/5/1/iranian-nobel-laureate-narges-mohammadi-hospitalised-as-health-deteriorates?traffic_source=rss",
          "date": "Fri, 01 May 2026 20:59:55 +0000",
          "source_country": "Iran",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "hospitalisation of Iranian Nobel laureate Narges Mohammadi",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Μερική υποχώρηση από το Ιράν: Λέει «ναι» σε διαπραγματεύσεις δίχως άρση του ναυτικού αποκλεισμού, βάζει στο τραπέζι πυρηνικά και άνοιγμα του Ορμούζ",
          "translated_title": null,
          "link": "https://www.protothema.gr/world/article/1812079/i-anatheorimeni-protasi-tou-iran-vima-pros-tis-ipa-gia-ta-stena-tou-ormouz-sunduazei-ta-purinika-me-tin-arsi-kuroseon/?utm_source=rss",
          "date": "Fri, 01 May 2026 23:25:00 +0300",
          "source_country": "Greece",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Iran nuclear negotiations willingness",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Trump says Iran seeks terms he ‘can’t agree to’ in latest peace proposal",
          "translated_title": null,
          "link": "https://www.aljazeera.com/news/2026/5/1/us-president-trump-not-satisfied-with-irans-latest-peace-proposal?traffic_source=rss",
          "date": "Fri, 01 May 2026 18:46:50 +0000",
          "source_country": "Iran",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "Trump criticizes Iran peace terms",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "US warns shippers against paying Strait of Hormuz tolls, ‘donations’",
          "translated_title": null,
          "link": "https://www.aljazeera.com/news/2026/5/1/us-warns-shippers-against-paying-strait-of-hormuz-tolls-donations?traffic_source=rss",
          "date": "Fri, 01 May 2026 17:18:43 +0000",
          "source_country": "Iran",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "US warns shippers over Hormuz tolls",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Waiting for a free Iran: the exiles who found a home in Armenia",
          "translated_title": null,
          "link": "https://oc-media.org/waiting-for-a-free-iran-the-exiles-who-found-a-home-in-armenia/",
          "date": "Thu, 30 Apr 2026 12:19:28 +0000",
          "source_country": "Georgia",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Armenia",
          "llm_final_country": "Iran",
          "llm_subject": "Iranian exiles finding refuge in Armenia",
          "llm_country_audit_corrected": true,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Poll finds 61 percent of Americans believe attacking Iran was a mistake",
          "translated_title": null,
          "link": "https://www.aljazeera.com/news/2026/5/1/poll-finds-61-percent-of-americans-believe-attacking-iran-was-a-mistake?traffic_source=rss",
          "date": "Fri, 01 May 2026 17:51:54 +0000",
          "source_country": "Iran",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iran",
          "llm_final_country": "Iran",
          "llm_subject": "US poll on Iran attack",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        }
      ]
    },
    "Iraq": {
      "index": 5.06,
      "raw_score": 2.5,
      "events": [
        {
          "title": "Iranian-linked drones target opposition camp in Iraqi Kurdistan",
          "translated_title": "Iranian-linked drones target opposition camp in Iraqi Kurdistan",
          "link": "https://www.newarab.com/news/iranian-linked-drones-target-opposition-camp-iraqi-kurdistan",
          "date": "Fri, 01 May 2026 16:03:33 +0100",
          "source_country": "Iraq",
          "category": "terrorism",
          "weight": 7.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iraq",
          "llm_final_country": "Iraq",
          "llm_subject": "Iran‑linked drones strike opposition camp in Iraqi Kurdistan",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Iraq starts work on Basra-Haditha oil pipeline: state media",
          "translated_title": null,
          "link": "https://www.newarab.com/news/iraq-starts-work-basra-haditha-oil-pipeline-state-media",
          "date": "Fri, 01 May 2026 17:06:30 +0100",
          "source_country": "Iraq",
          "category": "trade_agreement",
          "weight": -2.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Iraq",
          "llm_final_country": "Iraq",
          "llm_subject": "Iraq starts Basra-Haditha oil pipeline construction",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        }
      ]
    },
    "Syria": {
      "index": 4.65,
      "raw_score": 2.17,
      "events": [
        {
          "title": "ISIS Claims Responsibility for Assassination in Rural Aleppo Amid Rising Insecurity",
          "translated_title": "ISIS Claims Responsibility for Assassination in Rural Aleppo Amid Rising Insecurity",
          "link": "https://syrianobserver.com/security/isis-claims-responsibility-for-assassination-in-rural-aleppo-amid-rising-insecurity.html",
          "date": "Wed, 29 Apr 2026 21:01:27 +0000",
          "source_country": "Syria",
          "category": "terrorism",
          "weight": 7.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "ISIS claims Aleppo assassination",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Forced Resignations and Allegations of Duress at Lattakia Port",
          "translated_title": "Forced Resignations and Allegations of Duress at Lattakia Port",
          "link": "https://syrianobserver.com/society/forced-resignations-and-allegations-of-duress-at-lattakia-port.html",
          "date": "Wed, 29 Apr 2026 21:00:57 +0000",
          "source_country": "Syria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Forced resignations at Lattakia Port",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Between Amjad Youssef and Samir Kaakeh: Justice and Politics in Syria",
          "translated_title": "Between Amjad Youssef and Samir Kaakeh: Justice and Politics in Syria",
          "link": "https://syrianobserver.com/syrian-actors/between-amjad-youssef-and-samir-kaakeh-justice-and-politics-in-syria.html",
          "date": "Wed, 29 Apr 2026 21:00:53 +0000",
          "source_country": "Syria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Justice and politics in Syria",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Mass grave containing 55 bodies found in Syria’s Aleppo province",
          "translated_title": "Mass grave containing 55 bodies found in Syria’s Aleppo province",
          "link": "https://www.newarab.com/news/mass-grave-containing-55-bodies-found-syrias-aleppo-province",
          "date": "Fri, 01 May 2026 17:28:21 +0100",
          "source_country": "Iraq",
          "category": "humanitarian_crisis",
          "weight": 3.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": true,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Mass grave found in Aleppo province",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Syria",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Syria: 194 Detainees’ Children Reunited With Families",
          "translated_title": null,
          "link": "https://english.enabbaladi.net/archives/2026/05/syria-194-detainees-children-reunited-with-families/",
          "date": "Fri, 01 May 2026 10:20:43 +0000",
          "source_country": "Syria",
          "category": "humanitarian_crisis",
          "weight": 3.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Detainees' children reunited with families",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "US Supreme Court hears Haiti, Syria TPS case with wide-ranging implications - Al Jazeera",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMitgFBVV95cUxQdEoxY21rTEZhSDhpdkdjUGl5MFJkZUhLYzRiSGNNUGRMY0pjcHY2VUgtc0NHclhkRW90RG1rNUV5Z25qQTUwRlA0Tl9xanFwMUpFNC0tMkNWWV9lTmNhUjdmanU3YkxWbjU0VzFEU095dVZqUW9FcFpBSzROVnViRWd2NFVraVBMQkEtTmRVOGZYVDhxaEhKYUliZDEtWHJ1ZVBnSmFLQzkyZDN6TGdfcjlSbEplUdIBuwFBVV95cUxNRHVFNWc3d2J1YjdIV2lWMHdiTV9nY1BhMzJXNy0zX0haZ2ZFY1YtT2prcDFRZ20yZnpSQmtSV1A3bWZ6OTBaS0RfZ1lySWQ2a2FMUWZCblBrZW5fSVViTS04dFJma2J4RG94QVNhTjF2X2dDOThWVU9NeFA3SGo2NEpJcTE1MEJ2eUFlTl9zeXNHaE5GV25yR1U4YmkxRnFXY2dTdU1sVzBfMlA5eU1NU3U3OEVIbExZSzhJ?oc=5",
          "date": "Thu, 30 Apr 2026 04:37:06 GMT",
          "source_country": "Syria",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "US Supreme Court hears TPS case for Syria and Haiti",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Supreme Court weighs Trump bid to end Syrian, Haitian deportation protections - USA Today",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiyAFBVV95cUxNaGJMeVY3RV90QkxUazFPdW5VWk9Ld05HYWZ4dzhGc3ZaY2t0TkUxRTgzcDgtUDJHa3o0bUZPQkhxT3VMUV8xN2NSaTB4c2taZVBoLTd6T2Z2SDlXeEtIYWV0WEZnLXdvLWQzLUZvS3JxeGRIdTcyUXRPdWtTZ2ZESGZNOTVFUDdFdHloSDFMbVRaTHlEcjdnczZhU3Q2NmZ5WDBvbEJDMi1lTmtILXo5dGFnTERsaG5neTM1UEJsRFpndTM4enB6ZA?oc=5",
          "date": "Thu, 30 Apr 2026 15:55:00 GMT",
          "source_country": "Syria",
          "category": "diplomatic_tensions",
          "weight": 2.5,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "US court considers ending Syrian deportation protections",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "War-battered Syria now sells itself as a safe corridor amid regional conflict - Rocky Mount Telegram",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMigwJBVV95cUxQMnB4S0hSUU1Oc2dWRmNRYXhaeHMxR1l1b3pHeXpaV3lvY2xxUXVFbUF3RjNlaVFlOVNUbmtzNUxDSk5vY2NYeWVQSk81V1R2N0pSeTJKaGg3MHlXRDRKc0VlTFpISE11TmdiT0RXMjdNNjBSaFlUVDFtZXRVYXN1WjRpQ3hkQi11bERZTC1Uc1RjS2ZLY1RydE1uOUE3ZnhtYmNlbUplNy1pZzhQOEFxeFJ4Ty1TRkh3RjE5aFJDU1BwZFBsMTVORG1hLXc3U2xMNDJZRU1GXzYzT2hPSk5BU2dZcWcwSHdsQVV0d2RyeXdESUFCeXJJMTRRWE1jRzAzcUJR?oc=5",
          "date": "Fri, 01 May 2026 14:16:15 GMT",
          "source_country": "Syria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syria markets itself as safe corridor amid war",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria reportedly relies on Russian oil despite Western pivot - Türkiye Today",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMipgFBVV95cUxQRUJ4QTRzZkQ1czAzMUpaa3gzLXdlLWNFNmcyeVpYUmRGaWdpakFReG5UTUV4TXBSUTBlSE8ybkp6ak1zQzh2TmJhQl9hQko2YVFoVE9Fam03cWY4SEJxYUVyTUVkMnZCQnJpVm9keTc3UjhjREg2VFBWeHh0T00zNHBJcTBjLVZOX011cWljcmxCMExFYTFKazlZZ3FJNFhWQkJXZkRn?oc=5",
          "date": "Fri, 01 May 2026 10:59:23 GMT",
          "source_country": "Syria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syria relies on Russian oil despite Western shift",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Suspension of Trading in Damascus Securities Exchange Companies Pressures Confidence and Liquidity",
          "translated_title": null,
          "link": "https://syrianobserver.com/syrian-actors/suspension-of-trading-in-damascus-securities-exchange-companies-pressures-confidence-and-liquidity.html",
          "date": "Wed, 29 Apr 2026 21:00:29 +0000",
          "source_country": "Syria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Damascus stock trading suspension",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Turkish Groups Prepare $154 Million Syria Projects",
          "translated_title": null,
          "link": "https://english.enabbaladi.net/archives/2026/04/turkish-groups-prepare-154-million-syria-projects/",
          "date": "Thu, 30 Apr 2026 18:00:31 +0000",
          "source_country": "Syria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Turkish groups fund Syria projects",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syrian Central Bank Eyes Wider Powers, Digital Payments",
          "translated_title": null,
          "link": "https://english.enabbaladi.net/archives/2026/04/syrian-central-bank-eyes-wider-powers-digital-payments/",
          "date": "Thu, 30 Apr 2026 16:00:15 +0000",
          "source_country": "Syria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Syria",
          "llm_final_country": "Syria",
          "llm_subject": "Syrian central bank digital payments plan",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        }
      ]
    },
    "Bulgaria": {
      "index": 6.05,
      "raw_score": 3.43,
      "events": [
        {
          "title": "Bulgarian Voters, Worn Down by Corruption, Back New Coalition - The New York Times",
          "translated_title": "Bulgarian Voters, Worn Down by Corruption, Back New Coalition - The New York Times",
          "link": "https://news.google.com/rss/articles/CBMihgFBVV95cUxQcmhoMjNrb1BuNFVLcUZidC1kUEs4UlZiLXFKRmdBd3RFRUZkY3NiWHhJTG0xbi1KaDUwdDRPY1JEVnpPRjJ2RTZFcXl6NnhObFdjOXQ3U3JoNkRYM2J3elNTLTVwRTluVTdZTUVUUnJaSFhLNDQ5ZnB6OGktVGZwdXl2NVl6Zw?oc=5",
          "date": "Sun, 19 Apr 2026 07:00:00 GMT",
          "source_country": "Bulgaria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Bulgarian voters back new coalition",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Rumen Radev's party wins Bulgarian election - BBC",
          "translated_title": "Rumen Radev's party wins Bulgarian election - BBC",
          "link": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE9lUXBMb1p2T0g0b2gxc2dhbG9aRGZHSlpCOUZHaTBZQ3hDSENDTWZScGh3Tjh0RDRBQWZtSlhCUUxYREMwczJ3OWZWSS1GRU02cUpadXpMNTRuZw?oc=5",
          "date": "Mon, 20 Apr 2026 07:00:00 GMT",
          "source_country": "Bulgaria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Rumen Radev's party wins election",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria elections: Who’s running and what’s at stake? - Al Jazeera",
          "translated_title": "Bulgaria elections: Who’s running and what’s at stake? - Al Jazeera",
          "link": "https://news.google.com/rss/articles/CBMilgFBVV95cUxQbmNEc01CWlN1a0lyMHFVM2JtU0EyVFo5aWRTNWFQVXVRTnQ3WC02Sm5qaEF6aGtkRzlUY0VLbWhIXzNTV0F2TWFoenBWQ3NVc09Vb0I4SVdxb1RwdzRvakNJTGF3MHd1cmd2WlJ4cjVfMDVnNHA0bU9BRUg0eU5lSHRlYWZkdElKRVBuZmJyWnBmZ2dMR3fSAZsBQVVfeXFMT1JEajA4QTZYRWRSY3cwQ1hhdVlLQWRsQmdJcUxua0RqNVp6MFhINlZIc0kyNzlKdGkteTE5SHdnZmlzRlFGUnlORWlBNFhrT0Z4YVFycFVwVjBQQjU4ZzRDZHI2UnNocVc0bHI4Tzgtdl81Qm1Db2dlWDBTZlprSGNYdTkxektpSlpmdHRiU3dqazBFY0lGMF9RRGM?oc=5",
          "date": "Fri, 17 Apr 2026 07:00:00 GMT",
          "source_country": "Bulgaria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Overview of Bulgarian election candidates",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Bulgaria",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Europe Today: Russia-friendly Radev wins in Bulgaria as Orbán hints at lifting EU Ukraine loan veto - Euronews.com",
          "translated_title": "Europe Today: Russia-friendly Radev wins in Bulgaria as Orbán hints at lifting EU Ukraine loan veto - Euronews.com",
          "link": "https://news.google.com/rss/articles/CBMi0gFBVV95cUxNakFGci1aeXh2cDVJNjBLbTJCT1RrV1BsUG1HVGtzVmpWa0xTVUhfUFFOdkVGNGxlcWNPalZoaHdHdWxVanhFcUFXc3FObU10d2E3OFh6ZHo0bmluY3dSdDBKbWNQVDIwekc4RU81Qjd0SkJoejB4UEJaY3NjMTlPMV9SOWhsaDMxZFcyd1BTUE03QWlBa0tTT0x1eEJlUjZGb05PZjFBNnE3ZVZBZFJNQ3hoX0RLay1LcW53LVpxU1pKejIyVWVZaW1xUExLWGtxZEE?oc=5",
          "date": "Mon, 20 Apr 2026 07:00:00 GMT",
          "source_country": "Bulgaria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Radev victory and EU loan veto hints",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Bulgaria",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Bulgaria election: Ex-President Radev secures landslide victory - Al Jazeera",
          "translated_title": "Bulgaria election: Ex-President Radev secures landslide victory - Al Jazeera",
          "link": "https://news.google.com/rss/articles/CBMitgFBVV95cUxNYXktS1d4ZGw2Wno3Yi1kSGRNQkJTZFVDOVhZT2oxeXRLcXJRZU4zREhPZFNyNGljTEtkck1Id01uSzQ5Y0lsS2s0MEhrUE4yc29KbV84dFJPSUo5M3J4aVA0LWZTNVZOUmxtdnhrN3VtTjhJMV9BWDlpUGE4REJjek5KVXRqSEJXUWdRNWVhSUVQMUlJbm5HRzR2bGJVTGotNkdyc09aMnV1UXVHbEcyTHVYYzh5UdIBuwFBVV95cUxOVGwwVlhtU05VdWpWbklPelR2WXZSTzRMZ3kzb1RGTlVpeEF0THlsbVd1X1NiUE5BMllaUTJLOEtQdlNoS0VkR2FtMXIwUTByMW0tOUoyWkJVSEJuMEEzVUlRdmxIdEdPTlFNQ241d2p6N3R6aVpIcU45Vk1ZMDc0R2Izd2paWDNXSTJzU2VuTHlrY1l6UndMNVktT18zOTFhQWw5NUhsUDlBQ3A0TTBsVy1JaEEwWEE4NU5F?oc=5",
          "date": "Sun, 19 Apr 2026 07:00:00 GMT",
          "source_country": "Bulgaria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Radev landslide election win",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Йотова ще започне консултациите с партиите на 5 май",
          "translated_title": "Yotova will start consultations with the parties on May 5",
          "link": "https://www.dnevnik.bg/bulgaria/2026/05/01/4909556_iotova_shte_zapochne_konsultaciite_s_partiite_na_5_mai/?ref=rss",
          "date": "Fri, 01 May 2026 19:13:00 +0300",
          "source_country": "Bulgaria",
          "category": "political_instability",
          "weight": 4.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "President Yotova launches party consultations",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Bulgaria",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Свлачище между Смолян и Пампорово отнесе десетки метри от пътното платно (видео)",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/bulgaria/2026/05/01/4909573_svlachishte_mejdu_smolian_i_pamporovo_otnese_desetki/?ref=rss",
          "date": "Fri, 01 May 2026 20:01:00 +0300",
          "source_country": "Bulgaria",
          "category": "neutral",
          "weight": 0.0,
          "confidence": 1.0,
          "ai_model": "openrouter/free",
          "ai_category": true,
          "ai_reattributed": false,
          "llm_primary_country": "Bulgaria",
          "llm_final_country": "Bulgaria",
          "llm_subject": "Landslide damages road between Smolyan and Pamporovo in Bulgaria",
          "llm_country_audit_corrected": false,
          "ai_confidence_score": "100.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        }
      ]
    }
  },
  "history": [
    {
      "timestamp": "2026-04-29T23:29:09.208216",
      "main_index": 3.8,
      "index": 3.8,
      "type": "historical"
    },
    {
      "timestamp": "2026-04-30T02:30:34.326591",
      "main_index": 5.0,
      "index": 5.0,
      "type": "historical"
    },
    {
      "timestamp": "2026-04-30T11:29:50.025055",
      "main_index": 3.91,
      "index": 3.91,
      "type": "historical"
    },
    {
      "timestamp": "2026-04-30T20:40:02.923318",
      "main_index": 4.69,
      "index": 4.69,
      "type": "historical"
    },
    {
      "timestamp": "2026-04-30T21:24:12.950116",
      "main_index": 4.24,
      "index": 4.24,
      "type": "historical"
    },
    {
      "timestamp": "2026-04-30T23:30:57.803218",
      "main_index": 5.3,
      "index": 5.3,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-01T02:38:21.697160",
      "main_index": 4.35,
      "index": 4.35,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-01T07:07:59.427038",
      "main_index": 3.91,
      "index": 3.91,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-01T09:37:40.503449",
      "main_index": 4.33,
      "index": 4.33,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-01T11:19:23.934160",
      "main_index": 3.97,
      "index": 3.97,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-01T15:25:14.755478",
      "main_index": 3.05,
      "index": 3.05,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-01T17:01:49.313822",
      "main_index": 3.44,
      "index": 3.44,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-01T19:38:07.383090",
      "main_index": 3.87,
      "index": 3.87,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-01T20:55:36.225146",
      "main_index": 4.29,
      "index": 4.29,
      "type": "historical"
    },
    {
      "timestamp": "2026-05-01T22:59:16.478113",
      "main_index": 4.56,
      "index": 4.56,
      "type": "historical"
    }
  ],
  "forecast": [
    {
      "timestamp": "2026-05-01T23:59:16.478113",
      "index": 3.88,
      "main_index": 3.88,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-05-02T00:59:16.478113",
      "index": 3.85,
      "main_index": 3.85,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-05-02T01:59:16.478113",
      "index": 3.81,
      "main_index": 3.81,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-05-02T02:59:16.478113",
      "index": 3.77,
      "main_index": 3.77,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-05-02T03:59:16.478113",
      "index": 3.74,
      "main_index": 3.74,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-05-02T04:59:16.478113",
      "index": 3.7,
      "main_index": 3.7,
      "confidence": 0.3,
      "type": "forecast"
    }
  ],
  "methodology": {
    "name": "LLM Border Threat Taxonomy",
    "description": "OpenRouter free routing chooses the final country attribution and canonical threat category for each headline.",
    "weights": {
      "military_conflict": 8.0,
      "terrorism": 7.0,
      "border_security": 5.0,
      "political_instability": 4.0,
      "humanitarian_crisis": 3.0,
      "diplomatic_tensions": 2.5,
      "trade_agreement": -2.0,
      "neutral": 0.0
    },
    "formula": "PerCountry = 1 + 9*(1 - exp(-avg(weight)/5 * 1.2)); Composite = weighted_avg(PerCountry)",
    "scale": {
      "min": 1.0,
      "max": 10.0,
      "thresholds": {
        "STABLE": [
          1.0,
          4.0
        ],
        "ELEVATED": [
          4.0,
          7.0
        ],
        "CRITICAL": [
          7.0,
          10.0
        ]
      }
    }
  },
  "briefing": {
    "regional_summary_6h": {
      "slot_start": "2026-05-01T12:00:00Z",
      "slot_end": "2026-05-01T18:00:00Z",
      "generated_at": "2026-05-01T19:37:54Z",
      "next_refresh_at": "2026-05-02T00:00:00Z",
      "window_hours": 6,
      "source_event_count": 5,
      "source_countries": [
        "Iran",
        "Iraq",
        "Syria"
      ],
      "headline": "Iranian-linked drones strike Iraqi Kurdistan as Syria sees high-profile assassination and mass grave discovery",
      "bullets": [
        "Iranian-linked drones targeted an opposition camp in Iraqi Kurdistan during the window.",
        "A bombing killed the preacher of the Sayyida Zaynab shrine in rural Damascus.",
        "A mass grave containing 55 bodies was discovered in Aleppo province in Syria."
      ],
      "watch": "Monitor for retaliatory cross-border strikes from Iraqi Kurdistan into Iran."
    }
  }
};